/**
 * 個案資料卡產生器 - 標準字典與照護資料庫 V3.0 (Data JS)
 * 支援多國籍照服員第二語言：
 * 1. 越南語 (Tiếng Việt)
 * 2. 英語 (English)
 * 3. 印尼語 (Bahasa Indonesia)
 * 4. 菲律賓語 (Tagalog)
 * 5. 泰語 (ภาษาไทย)
 * 嚴守原則：醫療與長照臨床專業用語精準對照，絕不在外語欄位混入未翻譯之中文字元
 */

const CARE_DICTIONARY = {
  // 標題分類
  categories: {
    "病史": { vi: "Bệnh sử", en: "Medical History", id: "Riwayat Penyakit", fil: "Kasaysayan ng Medikal", th: "ประวัติการเจ็บป่วย" },
    "疾病史": { vi: "Bệnh sử", en: "Medical History", id: "Riwayat Penyakit", fil: "Kasaysayan ng Medikal", th: "ประวัติการเจ็บป่วย" },
    "外表意識": { vi: "Ý thức / Ngoại quan", en: "Consciousness / Appearance", id: "Tingkat Kesadaran", fil: "Kamalayan / Hitsura", th: "ระดับการรับรู้ / สภาพภายนอก" },
    "聽力與視力": { vi: "Thính lực / Thị lực", en: "Hearing & Vision", id: "Pendengaran & Penglihatan", fil: "Pandinig & Paningin", th: "การได้ยินและการมองเห็น" },
    "感官": { vi: "Thính lực / Thị lực", en: "Hearing & Vision", id: "Pendengaran & Penglihatan", fil: "Pandinig & Paningin", th: "การได้ยินและการมองเห็น" },
    "輔具與移位": { vi: "Dụng cụ hỗ trợ / Di chuyển", en: "Assistive Devices & Mobility", id: "Alat Bantu & Mobilisasi", fil: "Mga Pantulong & Paglipat", th: "อุปกรณ์ช่วยและการเคลื่อนย้าย" },
    "飲食形態": { vi: "Dạng thức ăn", en: "Diet Texture", id: "Bentuk Makanan", fil: "Uri ng Pagkain", th: "ลักษณะอาหาร" },
    "進食協助": { vi: "Hỗ trợ ăn uống", en: "Feeding Assistance", id: "Bantuan Makan", fil: "Tulong sa Pagkain", th: "การช่วยเหลือการรับประทาน" },
    "飲食": { vi: "Chế độ ăn uống", en: "Diet & Nutrition", id: "Pola Makan", fil: "Diyeta / Pagkain", th: "การรับประทานอาหาร" },
    "排泄照護": { vi: "Bài tiết", en: "Elimination Care", id: "Pola Buang Air", fil: "Pangangalaga sa Pagdumi at Pag-ihi", th: "การขับถ่าย" },
    "排泄": { vi: "Bài tiết / Vệ sinh", en: "Elimination / Hygiene", id: "Pola Buang Air", fil: "Pagdumi at Pag-ihi", th: "การขับถ่าย" },
    "重要注意事項": { vi: "Điểm cần lưu ý", en: "Important Precautions", id: "Peringatan Penting", fil: "Mahalagang Paalala", th: "ข้อควรระวังสำคัญ" },
    "注意事項": { vi: "Điểm cần lưu ý", en: "Precautions", id: "Peringatan Penting", fil: "Mahalagang Paalala", th: "ข้อควรระวังสำคัญ" },
    "性別": { vi: "Giới tính", en: "Gender", id: "Jenis Kelamin", fil: "Kasarian", th: "เพศ" },
    "男": { vi: "Nam", en: "Male", id: "Laki-laki", fil: "Lalaki", th: "ชาย" },
    "女": { vi: "Nữ", en: "Female", id: "Perempuan", fil: "Babae", th: "หญิง" }
  },

  // 常見病史 (含三高、十大常見慢性病、長照臨床診斷與中英文別名)
  medicalHistory: {
    "高血壓": { vi: "Cao huyết áp", en: "Hypertension (HTN)", id: "Hipertensi (Darah tinggi)", fil: "Mataas na presyon ng dugo", th: "ความดันโลหิตสูง" },
    "高血糖": { vi: "Đường huyết cao", en: "Hyperglycemia", id: "Gula darah tinggi", fil: "Mataas na asukal sa dugo", th: "น้ำตาลในเลือดสูง" },
    "高血脂": { vi: "Mỡ máu cao", en: "Hyperlipidemia", id: "Kolesterol tinggi", fil: "Mataas na kolesterol", th: "ไขมันในเลือดสูง" },
    "高血脂症": { vi: "Mỡ máu cao", en: "Hyperlipidemia", id: "Kolesterol tinggi", fil: "Mataas na kolesterol", th: "ไขมันในเลือดสูง" },
    "糖尿病": { vi: "Tiểu đường", en: "Diabetes (DM)", id: "Diabetes", fil: "Diyabetes", th: "โรคเบาหวาน" },
    "心臟病": { vi: "Bệnh tim mạch", en: "Heart Disease", id: "Penyakit jantung", fil: "Sakit sa puso", th: "โรคหัวใจ" },
    "心血管疾病": { vi: "Bệnh tim mạch", en: "Cardiovascular Disease", id: "Penyakit kardiovaskular", fil: "Sakit sa puso at ugat", th: "โรคหัวใจและหลอดเลือด" },
    "腦中風": { vi: "Tai biến mạch máu não (Đột quỵ)", en: "Stroke (CVA)", id: "Stroke", fil: "Stroke", th: "โรคหลอดเลือดสมอง" },
    "中風": { vi: "Tai biến mạch máu não (Đột quỵ)", en: "Stroke (CVA)", id: "Stroke", fil: "Stroke", th: "โรคหลอดเลือดสมอง" },
    "腦梗塞": { vi: "Nhồi máu não", en: "Cerebral Infarction", id: "Infark serebral", fil: "Cerebral infarction", th: "ภาวะสมองขาดเลือด" },
    "腦出血": { vi: "Xuất huyết não", en: "Cerebral Hemorrhage", id: "Perdarahan otak", fil: "Pagdurugo sa utak", th: "ภาวะเลือดออกในสมอง" },
    "失智症": { vi: "Sa sút trí tuệ", en: "Dementia", id: "Demensia", fil: "Dementia (Ulyanin)", th: "ภาวะสมองเสื่อม" },
    "失智": { vi: "Sa sút trí tuệ", en: "Dementia", id: "Demensia", fil: "Dementia", th: "ภาวะสมองเสื่อม" },
    "阿茲海默症": { vi: "Bệnh Alzheimer", en: "Alzheimer's Disease", id: "Penyakit Alzheimer", fil: "Sakit na Alzheimer", th: "โรคอัลไซเมอร์" },
    "血管性失智症": { vi: "Sa sút trí tuệ mạch máu", en: "Vascular Dementia", id: "Demensia vaskular", fil: "Vascular dementia", th: "ภาวะสมองเสื่อมจากหลอดเลือด" },
    "癌症": { vi: "Ung thư", en: "Cancer", id: "Kanker", fil: "Kanser", th: "โรคมะเร็ง" },
    "惡性腫瘤": { vi: "Khối u ác tính", en: "Malignant Tumor", id: "Tumor ganas", fil: "Malignant tumor", th: "เนื้องอกร้าย" },
    "心律不整": { vi: "Rối loạn nhịp tim", en: "Arrhythmia", id: "Aritmia jantung", fil: "Irregular na tibok ng puso", th: "หัวใจเต้นผิดจังหวะ" },
    "心房顫動": { vi: "Rung nhĩ (AFib)", en: "Atrial Fibrillation (Afib)", id: "Fibrilasi atrium (AFib)", fil: "Atrial fibrillation", th: "ภาวะหัวใจห้องบนสั่นพลิ้ว" },
    "慢性腎臟病": { vi: "Bệnh thận mạn tính", en: "Chronic Kidney Disease (CKD)", id: "Penyakit ginjal kronis", fil: "Sakit sa bato (CKD)", th: "โรคไตเรื้อรัง" },
    "腎衰竭": { vi: "Suy thận", en: "Kidney Failure", id: "Gagal ginjal", fil: "Sakit sa bato (Kidney failure)", th: "ไตวาย" },
    "洗腎": { vi: "Chạy thận nhân tạo (Lọc máu)", en: "Hemodialysis", id: "Cuci darah (Dialisis)", fil: "Dialysis", th: "การฟอกไต" },
    "透析": { vi: "Lọc máu (Thận)", en: "Dialysis", id: "Dialisis", fil: "Dialysis", th: "การล้างไต" },
    "痛風": { vi: "Bệnh gút (Gout)", en: "Gout", id: "Asam urat (Gout)", fil: "Gout", th: "โรคเกาต์" },
    "痛風性關節炎": { vi: "Viêm khớp do gút", en: "Gouty Arthritis", id: "Artritis gout", fil: "Gouty arthritis", th: "โรคข้ออักเสบจากเกาต์" },
    "骨質疏鬆": { vi: "Loãng xương", en: "Osteoporosis", id: "Osteoporosis", fil: "Osteoporosis (Marupok na buto)", th: "โรคกระดูกพรุน" },
    "骨鬆": { vi: "Loãng xương", en: "Osteoporosis", id: "Osteoporosis", fil: "Osteoporosis", th: "โรคกระดูกพรุน" },
    "氣喘": { vi: "Hen suyễn", en: "Asthma", id: "Asma", fil: "Hika", th: "โรคหอบหืด" },
    "帕金森氏症": { vi: "Bệnh Parkinson", en: "Parkinson's Disease", id: "Penyakit Parkinson", fil: "Parkinson's disease", th: "โรคพาร์กินสัน" },
    "巴金森氏症": { vi: "Bệnh Parkinson", en: "Parkinson's Disease", id: "Penyakit Parkinson", fil: "Parkinson's disease", th: "โรคพาร์กินสัน" },
    "帕金森": { vi: "Bệnh Parkinson", en: "Parkinson's Disease", id: "Penyakit Parkinson", fil: "Parkinson's disease", th: "โรคพาร์กินสัน" },
    "巴金森": { vi: "Bệnh Parkinson", en: "Parkinson's Disease", id: "Penyakit Parkinson", fil: "Parkinson's disease", th: "โรคพาร์กินสัน" },
    "心衰竭": { vi: "Suy tim", en: "Heart Failure (CHF)", id: "Gagal jantung", fil: "Heart failure", th: "ภาวะหัวใจล้มเหลว" },
    "心臟衰竭": { vi: "Suy tim", en: "Heart Failure (CHF)", id: "Gagal jantung", fil: "Heart failure", th: "ภาวะหัวใจล้มเหลว" },
    "冠心症": { vi: "Bệnh mạch vành", en: "Coronary Artery Disease (CAD)", id: "Penyakit jantung koroner", fil: "Coronary artery disease", th: "โรคหลอดเลือดหัวใจ" },
    "冠心病": { vi: "Bệnh mạch vành", en: "Coronary Heart Disease (CAD)", id: "Penyakit jantung koroner", fil: "Coronary heart disease", th: "โรคหลอดเลือดหัวใจ" },
    "心肌梗塞": { vi: "Nhồi máu cơ tim", en: "Myocardial Infarction (AMI)", id: "Infark miokard", fil: "Atake sa puso", th: "กล้ามเนื้อหัวใจตายเฉียบพลัน" },
    "心絞痛": { vi: "Cơn đau thắt ngực", en: "Angina Pectoris", id: "Angina pektoris", fil: "Paninikip ng dibdib", th: "อาการเจ็บแน่นหน้าอก" },
    "慢性阻塞性肺病": { vi: "Bệnh phổi tắc nghẽn mạn tính (COPD)", en: "COPD", id: "PPOK (COPD)", fil: "COPD", th: "โรคปอดอุดกั้นเรื้อรัง" },
    "COPD": { vi: "Bệnh phổi tắc nghẽn (COPD)", en: "COPD", id: "PPOK (COPD)", fil: "COPD", th: "โรคปอดอุดกั้นเรื้อรัง" },
    "肺氣腫": { vi: "Khí phế thũng", en: "Pulmonary Emphysema", id: "Emfisema paru", fil: "Emphysema", th: "ถุงลมโป่งพอง" },
    "退化性關節炎": { vi: "Thoái hóa khớp", en: "Osteoarthritis (OA)", id: "Osteoartritis", fil: "Osteoarthritis", th: "โรคข้อเสื่อม" },
    "關節炎": { vi: "Viêm khớp", en: "Arthritis", id: "Radang sendi (Artritis)", fil: "Arthritis", th: "โรคข้ออักเสบ" },
    "類風濕性關節炎": { vi: "Viêm khớp dạng thấp", en: "Rheumatoid Arthritis", id: "Artritis reumatoid", fil: "Rheumatoid arthritis", th: "โรคข้ออักเสบรูมาตอยด์" },
    "壓瘡": { vi: "Loét tì đè", en: "Pressure Ulcer (Bedsore)", id: "Luka tekan (Dekubitus)", fil: "Bedsore / Ulser sa presyon", th: "แผลกดทับ" },
    "褥瘡": { vi: "Loét tì đè (nằm liệt)", en: "Bedsore (Decubitus)", id: "Luka dekubitus", fil: "Bedsore", th: "แผลกดทับ" },
    "白內障": { vi: "Đục thủy tinh thể", en: "Cataract", id: "Katarak", fil: "Katarata", th: "ต้อกระจก" },
    "青光眼": { vi: "Bệnh cườm nước (Glaucoma)", en: "Glaucoma", id: "Glaukoma", fil: "Glaucoma", th: "ต้อหิน" },
    "黃斑部病變": { vi: "Thoái hóa điểm vàng", en: "Macular Degeneration", id: "Degenerasi makula", fil: "Macular degeneration", th: "โรคจอประสาทตาเสื่อม" },
    "貧血": { vi: "Thiếu máu", en: "Anemia", id: "Anemia (Kurang darah)", fil: "Anemia", th: "ภาวะโลหิตจาง" },
    "肝硬化": { vi: "Xơ gan", en: "Liver Cirrhosis", id: "Sirosis hati", fil: "Cirrhosis ng atay", th: "โรคตับแข็ง" },
    "B型肝炎": { vi: "Viêm gan B", en: "Hepatitis B", id: "Hepatitis B", fil: "Hepatitis B", th: "ไวรัสตับอักเสบบี" },
    "C型肝炎": { vi: "Viêm gan C", en: "Hepatitis C", id: "Hepatitis C", fil: "Hepatitis C", th: "ไวรัสตับอักเสบซี" },
    "攝護腺肥大": { vi: "Phì đại tuyến tiền liệt", en: "Enlarged Prostate (BPH)", id: "Pembesaran prostat (BPH)", fil: "Enlarged prostate (BPH)", th: "ต่อมลูกหมากโต" },
    "前列腺肥大": { vi: "Phì đại tuyến tiền liệt", en: "Enlarged Prostate (BPH)", id: "Pembesaran prostat (BPH)", fil: "Enlarged prostate (BPH)", th: "ต่อมลูกหมากโต" },
    "癲癇": { vi: "Động kinh", en: "Epilepsy", id: "Epilepsi (Ayan)", fil: "Epilepsy", th: "โรคลมชัก" },
    "憂鬱症": { vi: "Trầm cảm", en: "Depression", id: "Depresi", fil: "Depresyon", th: "โรคซึมเศร้า" },
    "躁鬱症": { vi: "Rối loạn lưỡng cực", en: "Bipolar Disorder", id: "Gangguan bipolar", fil: "Bipolar disorder", th: "โรคอารมณ์สองขั้ว" },
    "思覺失調症": { vi: "Tâm thần phân liệt", en: "Schizophrenia", id: "Skizofrenia", fil: "Schizophrenia", th: "โรคจิตเภท" },
    "失眠": { vi: "Mất ngủ", en: "Insomnia", id: "Insomnia (Sulit tidur)", fil: "Insomnia", th: "นอนไม่หลับ" },
    "胃食道逆流": { vi: "Trào ngược dạ dày thực quản (GERD)", en: "GERD (Acid Reflux)", id: "GERD (Asam lambung)", fil: "Acid reflux (GERD)", th: "กรดไหลย้อน" },
    "胃潰瘍": { vi: "Loét dạ dày", en: "Gastric Ulcer", id: "Tukak lambung", fil: "Ulser sa tiyan", th: "แผลในกระเพาะอาหาร" },
    "十二指腸潰瘍": { vi: "Loét tá tràng", en: "Duodenal Ulcer", id: "Tukak duodenum", fil: "Duodenal ulcer", th: "แผลในลำไส้เล็กส่วนต้น" },
    "便秘": { vi: "Táo bón", en: "Constipation", id: "Konstipasi (Sembelit)", fil: "Pagtitibi (Constipation)", th: "ท้องผูก" },
    "腹瀉": { vi: "Tiêu chảy", en: "Diarrhea", id: "Diare", fil: "Pagtatae", th: "ท้องเสีย" },
    "泌尿道感染": { vi: "Nhiễm trùng đường tiết niệu (UTI)", en: "Urinary Tract Infection (UTI)", id: "Infeksi saluran kemih (ISK)", fil: "UTI", th: "การติดเชื้อทางเดินปัสสาวะ" },
    "尿道感染": { vi: "Nhiễm trùng đường tiết niệu (UTI)", en: "Urinary Tract Infection (UTI)", id: "Infeksi saluran kemih (ISK)", fil: "UTI", th: "การติดเชื้อทางเดินปัสสาวะ" },
    "疥瘡": { vi: "Bệnh ghẻ", en: "Scabies", id: "Kudis (Skabies)", fil: "Galis-aso (Scabies)", th: "โรคหิด" },
    "肺炎": { vi: "Viêm phổi", en: "Pneumonia", id: "Pneumonia (Radang paru)", fil: "Pulmunya", th: "โรคปอดบวม" },
    "骨折": { vi: "Gãy xương", en: "Fracture", id: "Patah tulang (Fraktur)", fil: "Bali sa buto", th: "กระดูกหัก" },
    "髖關節骨折": { vi: "Gãy xương khớp háng", en: "Hip Fracture", id: "Patah tulang panggul", fil: "Bali sa balakang", th: "กระดูกสะโพกหัก" },
    "蜂窩性組織炎": { vi: "Viêm mô tế bào", en: "Cellulitis", id: "Selulitis", fil: "Cellulitis", th: "การติดเชื้อเนื้อเยื่อใต้ผิวหนัง" },
    "下肢水腫": { vi: "Phù chân", en: "Leg Edema", id: "Edema kaki (Bengkak)", fil: "Manas sa binti", th: "ขาบวมน้ำ" },
    "水腫": { vi: "Phù nề", en: "Edema", id: "Edema (Bengkak)", fil: "Manas", th: "อาการบวมน้ำ" },
    "吞嚥困難": { vi: "Khó nuốt", en: "Dysphagia (Swallowing difficulty)", id: "Disfagia (Sulit menelan)", fil: "Nahihirapan lumunok", th: "กลืนลำบาก" },
    "吞嚥障礙": { vi: "Rối loạn nuốt", en: "Dysphagia", id: "Gangguan menelan", fil: "Hirap lumunok", th: "ความผิดปกติในการกลืน" },
    "失語症": { vi: "Chứng mất ngôn ngữ", en: "Aphasia", id: "Afasia (Sulit bicara)", fil: "Aphasia (Hirap magsalita)", th: "ภาวะสูญเสียการสื่อความ" },
    "偏癱": { vi: "Liệt nửa người", en: "Hemiplegia (Half paralysis)", id: "Hemiplegia (Lumpuh sebelah)", fil: "Paralisado ang kalahati", th: "อัมพาตครึ่งซีก" },
    "左側偏癱": { vi: "Liệt nửa người bên trái", en: "Left Hemiplegia", id: "Lumpuh sebelah kiri", fil: "Paralisado ang kaliwang bahagi", th: "อัมพาตครึ่งซีกซ้าย" },
    "右側偏癱": { vi: "Liệt nửa người bên phải", en: "Right Hemiplegia", id: "Lumpuh sebelah kanan", fil: "Paralisado ang kanang bahagi", th: "อัมพาตครึ่งซีกขวา" },
    "截肢": { vi: "Cắt cụt chi", en: "Amputation", id: "Amputasi", fil: "Naputulan ng paa/kamay", th: "การตัดแขนหรือขา" },
    "膽結石": { vi: "Sỏi mật", en: "Gallstones", id: "Batu empedu", fil: "Bato sa apdo", th: "นิ่วในถุงน้ำดี" },
    "腎結石": { vi: "Sỏi thận", en: "Kidney Stones", id: "Batu ginjal", fil: "Bato sa bato", th: "นิ่วในไต" },
    "重聽": { vi: "Lãng tai (nặng tai)", en: "Hearing Impairment", id: "Gangguan pendengaran", fil: "Mahina ang pandinig", th: "หูตึง / การได้ยินบกพร่อง" },
    "視力障礙": { vi: "Khiếm thị (suy giảm thị lực)", en: "Visual Impairment", id: "Gangguan penglihatan", fil: "Malabo ang mata", th: "สายตาเลือนราง" },
    "無特殊病史": { vi: "Không có tiền sử bệnh đặc biệt", en: "No special medical history", id: "Tidak ada riwayat penyakit khusus", fil: "Walang espesyal na sakit", th: "ไม่มีประวัติโรคประจำตัวพิเศษ" }
  },

  // 外表意識狀態
  consciousness: {
    "清醒": { vi: "Tỉnh táo", en: "Alert / Conscious", id: "Sadar penuh (Compos mentis)", fil: "Gising / Alerto", th: "รู้สึกตัวดี" },
    "混亂": { vi: "Lẫn lộn", en: "Confused", id: "Bingung (Konfusi)", fil: "Nalilito", th: "สับสน" },
    "譫妄": { vi: "Mê sảng", en: "Delirium", id: "Delirium", fil: "Delirium (Medyo tuliro)", th: "เพ้อ สับสนเฉียบพลัน" },
    "嗜睡": { vi: "Ngủ gà", en: "Drowsy / Somnolent", id: "Mengantuk berat (Somnolen)", fil: "Inaantok / Matamlay", th: "ง่วงซึม" },
    "木僵": { vi: "Sững sờ (Stupor)", en: "Stupor", id: "Stupor", fil: "Stupor (Halos walang kibo)", th: "เซื่องซึมมาก" },
    "昏迷": { vi: "Hôn mê", en: "Coma", id: "Koma", fil: "Comatose (Walang malay)", th: "หมดสติ / โคม่า" },
    "半昏迷": { vi: "Bán hôn mê", en: "Semi-coma", id: "Semi-koma", fil: "Kalahating walang malay", th: "กึ่งหมดสติ" },
  },

  // 聽力狀態
  sensoryHearing: {
    "正常": { vi: "Bình thường", en: "Normal", id: "Normal", fil: "Normal", th: "ปกติ" },
    "聽力正常": { vi: "Bình thường", en: "Normal", id: "Normal", fil: "Normal", th: "ปกติ" },
    "重聽": { vi: "Lãng tai (nặng tai)", en: "Hard of Hearing", id: "Kurang dengar", fil: "Mahina ang pandinig", th: "หูตึง" },
    "輕度重聽": { vi: "Lãng tai nhẹ", en: "Mild Hearing Loss", id: "Kurang dengar ringan", fil: "Bahagyang mahina ang pandinig", th: "หูตึงเล็กน้อย" },
    "需戴助聽器": { vi: "Cần đeo máy trợ thính", en: "Needs Hearing Aid", id: "Perlu alat bantu dengar", fil: "Kailangan ng hearing aid", th: "ต้องใช้เครื่องช่วยฟัง" },
    "需大聲說話": { vi: "Cần nói to", en: "Needs Loud Voice", id: "Perlu bicara keras", fil: "Kailangang lakasan ang boses", th: "ต้องพูดเสียงดัง" },
    "需大聲面對面說話": { vi: "Cần nói to trực diện", en: "Needs Loud Face-to-Face Voice", id: "Perlu bicara keras langsung", fil: "Kailangang lakasan ang boses", th: "ต้องพูดเสียงดังต่อหน้า" },
    "嚴重重聽": { vi: "Lãng tai nặng", en: "Severe Hearing Loss", id: "Tuli berat", fil: "Malubhang pagkabingi", th: "หูตึงรุนแรง" },
    "全聾": { vi: "Điếc hoàn toàn", en: "Deafness", id: "Tuli total", fil: "Bingi", th: "หูหนวกสนิท" },
    "中耳炎": { vi: "Viêm tai giữa", en: "Otitis Media", id: "Otitis media", fil: "Otitis media", th: "หูชั้นกลางอักเสบ" },
    "耳膜穿孔": { vi: "Thủng màng nhĩ", en: "Tympanic Perforation", id: "Gendang telinga pecah", fil: "Butas na eardrum", th: "แก้วหูทะลุ" },
    "單耳聽損": { vi: "Giảm thính lực một bên tai", en: "Unilateral Hearing Loss", id: "Gangguan pendengaran sepihak", fil: "Pagkabingi sa isang tainga", th: "สูญเสียการได้ยินข้างเดียว" },
    "耳鳴": { vi: "Ù tai", en: "Tinnitus", id: "Tinitus (telinga berdenging)", fil: "Tinnitus", th: "เสียงในหู" },
    "無法判斷": { vi: "Không thể đánh giá", en: "Unable to Assess", id: "Tidak dapat dinilai", fil: "Hindi masuri", th: "ไม่สามารถประเมินได้" },
    "不知道": { vi: "Không rõ (Chưa xác định)", en: "Unknown / Unclear", id: "Tidak diketahui", fil: "Hindi alam", th: "ไม่ทราบแน่ชัด" },
    "無法評估": { vi: "Không thể đánh giá", en: "Unable to Assess", id: "Tidak dapat dinilai", fil: "Hindi masuri", th: "ไม่สามารถประเมินได้" },
    "不清楚": { vi: "Không rõ ràng", en: "Unclear", id: "Tidak jelas", fil: "Hindi malinaw", th: "ไม่ชัดเจน" },
    "未評估": { vi: "Chưa đánh giá", en: "Not Assessed", id: "Belum dinilai", fil: "Hindi nasuri", th: "ยังไม่ได้ประเมิน" },
    "難以判斷": { vi: "Khó đánh giá", en: "Difficult to Assess", id: "Sulit dinilai", fil: "Mahirap suriin", th: "ยากที่จะประเมิน" },
    "意識障礙無法評估": { vi: "Rối loạn ý thức không thể đánh giá", en: "Unassessable due to consciousness disorder", id: "Gangguan kesadaran tidak dapat dinilai", fil: "Hindi masuri", th: "ประเมินไม่ได้เนื่องจากระดับความรู้สึกตัว" }
  },

  // 視力狀態
  sensoryVision: {
    "正常": { vi: "Bình thường", en: "Normal", id: "Normal", fil: "Normal", th: "ปกติ" },
    "視力正常": { vi: "Bình thường", en: "Normal", id: "Normal", fil: "Normal", th: "ปกติ" },
    "視力模糊退化": { vi: "Thị lực mờ suy giảm", en: "Blurred / Reduced Vision", id: "Penglihatan kabur", fil: "Malabo ang paningin", th: "สายตาพร่ามัวเสื่อม" },
    "視力模糊": { vi: "Thị lực mờ", en: "Blurred Vision", id: "Penglihatan kabur", fil: "Malabo ang paningin", th: "สายตาพร่ามัว" },
    "需戴眼鏡": { vi: "Cần đeo kính", en: "Needs Glasses", id: "Perlu kacamata", fil: "Kailangan ng salamin", th: "ต้องใส่แว่นตา" },
    "白內障": { vi: "Đục thủy tinh thể", en: "Cataract", id: "Katarak", fil: "Katarata", th: "ต้อกระจก" },
    "青光眼": { vi: "Bệnh cườm nước", en: "Glaucoma", id: "Glaukoma", fil: "Glaucoma", th: "ต้อหิน" },
    "弱視": { vi: "Nhược thị", en: "Amblyopia (Lazy Eye)", id: "Mata malas (Ambliopia)", fil: "Mahinang paningin", th: "ตาขี้เกียจ" },
    "單眼失明": { vi: "Hỏng một mắt", en: "Monocular Blindness", id: "Buta sebelah", fil: "Bulag ang isang mata", th: "ตาบอดข้างเดียว" },
    "全盲": { vi: "Khiếm thị hoàn toàn (Mù)", en: "Blindness", id: "Tunanetra total (Buta)", fil: "Bulag", th: "ตาบอดสนิท" },
    "病毒感染": { vi: "Nhiễm virus", en: "Viral infection", id: "Infeksi virus", fil: "Impeksyon ng virus", th: "การติดเชื้อไวรัส" },
    "右眼病毒感染": { vi: "Nhiễm virus mắt phải", en: "Right eye viral infection", id: "Infeksi virus mata kanan", fil: "Impeksyon ng virus sa kanang mata", th: "การติดเชื้อไวรัสที่ตาขวา" },
    "左眼病毒感染": { vi: "Nhiễm virus mắt trái", en: "Left eye viral infection", id: "Infeksi virus mata kiri", fil: "Impeksyon ng virus sa kaliwang mata", th: "การติดเชื้อไวรัสที่ตาซ้าย" },
    "黃斑部病變": { vi: "Thoái hóa điểm vàng", en: "Macular Degeneration", id: "Degenerasi makula", fil: "Macular degeneration", th: "โรคจอประสาทตาเสื่อม" },
    "視神經萎縮": { vi: "Teo dây thần kinh thị giác", en: "Optic Nerve Atrophy", id: "Atrofi saraf optik", fil: "Optic nerve atrophy", th: "ประสาทตาฝ่อ" },
    "角膜白斑": { vi: "Đục giác mạc (sẹo)", en: "Corneal leukoma", id: "Leukoma kornea", fil: "Leukoma sa kornea", th: "แผลเป็นที่กระจกตา" },
    "視網膜病變": { vi: "Bệnh võng mạc", en: "Retinopathy", id: "Retinopati", fil: "Retinopathy", th: "โรคจอตา" },
    "角膜炎": { vi: "Viêm giác mạc", en: "Keratitis", id: "Keratitis", fil: "Keratitis", th: "กระจกตาอักเสบ" },
    "斜視": { vi: "Lác mắt (lé)", en: "Strabismus (Squint)", id: "Mata juling", fil: "Banlag / Duling", th: "ตาเหล่" },
    "無法判斷": { vi: "Không thể đánh giá", en: "Unable to Assess", id: "Tidak dapat dinilai", fil: "Hindi masuri", th: "ไม่สามารถประเมินได้" },
    "不知道": { vi: "Không rõ (Chưa xác định)", en: "Unknown / Unclear", id: "Tidak diketahui", fil: "Hindi alam", th: "ไม่ทราบแน่ชัด" },
    "無法評估": { vi: "Không thể đánh giá", en: "Unable to Assess", id: "Tidak dapat dinilai", fil: "Hindi masuri", th: "ไม่สามารถประเมินได้" },
    "不清楚": { vi: "Không rõ ràng", en: "Unclear", id: "Tidak jelas", fil: "Hindi malinaw", th: "ไม่ชัดเจน" },
    "未評估": { vi: "Chưa đánh giá", en: "Not Assessed", id: "Belum dinilai", fil: "Hindi nasuri", th: "ยังไม่ได้ประเมิน" },
    "難以判斷": { vi: "Khó đánh giá", en: "Difficult to Assess", id: "Sulit dinilai", fil: "Mahirap suriin", th: "ยากที่จะประเมิน" },
    "意識障礙無法評估": { vi: "Rối loạn ý thức không thể đánh giá", en: "Unassessable due to consciousness disorder", id: "Gangguan kesadaran tidak dapat dinilai", fil: "Hindi masuri", th: "ประเมินไม่ได้เนื่องจากระดับความรู้สึกตัว" }
  },

  // 飲食形態
  dietTexture: {
    "正常餐": { vi: "Cơm bình thường", en: "Regular Diet", id: "Makanan biasa / normal", fil: "Normal na pagkain", th: "อาหารธรรมดา" },
    "普通餐": { vi: "Cơm bình thường", en: "Regular Diet", id: "Makanan biasa / normal", fil: "Normal na pagkain", th: "อาหารธรรมดา" },
    "剪菜飯": { vi: "Cơm cắt nhỏ", en: "Cut / Chopped Diet", id: "Makanan dipotong kecil", fil: "Hiniwang pagkain", th: "อาหารหั่นชิ้นเล็ก" },
    "攪菜粥": { vi: "Cháo xay", en: "Blended Porridge", id: "Bubur saring / blender", fil: "Nilagang lugaw na giniling", th: "โจ๊กปั่น" },
    "軟質飲食": { vi: "Thức ăn mềm", en: "Soft Diet", id: "Makanan lunak", fil: "Malambot na pagkain", th: "อาหารอ่อน" },
    "軟食": { vi: "Thức ăn mềm", en: "Soft Diet", id: "Makanan lunak", fil: "Malambot na pagkain", th: "อาหารอ่อน" },
    "碎食飲食": { vi: "Thức ăn băm nhỏ", en: "Minced Diet", id: "Makanan cincang halus", fil: "Giniling na pagkain", th: "อาหารสับละเอียด" },
    "碎食": { vi: "Thức ăn băm nhỏ", en: "Minced Diet", id: "Makanan cincang halus", fil: "Giniling na pagkain", th: "อาหารสับละเอียด" },
    "流質飲食": { vi: "Thức ăn lỏng", en: "Full Liquid Diet", id: "Makanan cair", fil: "Likidong pagkain", th: "อาหารเหลว" },
    "流質": { vi: "Thức ăn lỏng", en: "Liquid Diet", id: "Makanan cair", fil: "Likidong pagkain", th: "อาหารเหลว" },
    "低鹽飲食": { vi: "Ăn giảm muối", en: "Low-Sodium Diet", id: "Rendah garam", fil: "Mababang asin", th: "อาหารลดเค็ม" },
    "糖尿病低糖餐": { vi: "Chế độ ăn giảm đường", en: "Diabetic Diet", id: "Rendah gula (diabetes)", fil: "Mababang asukal", th: "อาหารเบาหวาน" },
    "低糖飲食": { vi: "Chế độ ăn giảm đường", en: "Low Sugar Diet", id: "Rendah gula", fil: "Mababang asukal", th: "อาหารน้ำตาลต่ำ" },
    "限制水分": { vi: "Hạn chế lượng nước", en: "Fluid Restricted Diet", id: "Batasi cairan", fil: "Limitadong tubig", th: "จำกัดน้ำ" },
    "素食": { vi: "Ăn chay", en: "Vegetarian Diet", id: "Makanan vegetarian", fil: "Vegetarian", th: "อาหารมังสวิรัติ" }
  },

  // 進食協助 (獨立項目)
  dietAssistance: {
    "可自行進食": { vi: "Tự ăn uống được", en: "Independent Eating", id: "Dapat makan sendiri", fil: "Kayang kumain mag-isa", th: "รับประทานอาหารได้เอง" },
    "自行進食": { vi: "Tự ăn uống được", en: "Independent Eating", id: "Dapat makan sendiri", fil: "Kayang kumain mag-isa", th: "รับประทานอาหารได้เอง" },
    "需部分協助進食": { vi: "Cần hỗ trợ một phần", en: "Needs Partial Assistance", id: "Perlu bantuan sebagian", fil: "Kailangan ng bahagyang tulong", th: "ต้องการความช่วยเหลือบางส่วน" },
    "部分協助": { vi: "Cần hỗ trợ một phần", en: "Partial Assistance", id: "Perlu bantuan sebagian", fil: "Kailangan ng bahagyang tulong", th: "ต้องการความช่วยเหลือบางส่วน" },
    "需完全協助餵食": { vi: "Cần hỗ trợ đút ăn hoàn toàn", en: "Needs Total Assistance (Feeding)", id: "Perlu disuapi penuh", fil: "Kailangang subuan nang buo", th: "ต้องช่วยป้อนอาหารทั้งหมด" },
    "完全餵食": { vi: "Cần hỗ trợ đút ăn hoàn toàn", en: "Total Feeding Assistance", id: "Perlu disuapi penuh", fil: "Kailangang subuan nang buo", th: "ต้องช่วยป้อนอาหารทั้งหมด" },
    "鼻胃管灌食": { vi: "Ăn qua ống thông mũi dạ dày (NG tube)", en: "Nasogastric (NG) Tube Feeding", id: "Makan lewat selang NGT", fil: "Pinapakain sa NGT (Sonde)", th: "ให้อาหารทางสายยางจมูก (NG tube)" },
    "鼻胃管": { vi: "Ăn qua ống thông mũi dạ dày (NG tube)", en: "NG Tube Feeding", id: "Makan lewat selang NGT", fil: "Pinapakain sa NGT (Sonde)", th: "ให้อาหารทางสายยางจมูก (NG tube)" },
    "胃造口灌食": { vi: "Ăn qua ống thông dạ dày (PEG)", en: "Gastrostomy (PEG) Feeding", id: "Makan lewat selang PEG", fil: "Pinapakain sa PEG", th: "ให้อาหารทางสายยางหน้าท้อง (PEG)" },
    "胃造口": { vi: "Ăn qua ống thông dạ dày (PEG)", en: "PEG Tube Feeding", id: "Makan lewat selang PEG", fil: "Pinapakain sa PEG", th: "ให้อาหารทางสายยางหน้าท้อง (PEG)" }
  },

  // 輔具
  aids: {
    "輪椅": { vi: "Xe lăn", en: "Wheelchair", id: "Kursi roda", fil: "Wheelchair", th: "รถเข็นวีลแชร์" },
    "助行器": { vi: "Khung tập đi", en: "Walker", id: "Walker / Alat bantu jalan", fil: "Walker", th: "วอล์กเกอร์ช่วยเดิน" },
    "單拐": { vi: "Gậy đơn", en: "Single Cane", id: "Tongkat satu kaki", fil: "Tungkod (Single cane)", th: "ไม้เท้าเดี่ยว" },
    "四腳拐": { vi: "Gậy 4 chân", en: "Quad Cane", id: "Tongkat kaki empat (Quad cane)", fil: "Quad cane (4 na paa)", th: "ไม้เท้า 4 ขา" },
    "拐杖": { vi: "Gậy chống", en: "Crutches", id: "Tongkat ketiak", fil: "Saklay", th: "ไม้ค้ำยัน" },
    "氣墊床": { vi: "Đệm khí chống loét", en: "Air Mattress (Anti-bedsore)", id: "Matras angin anti-decubitus", fil: "Air mattress (Anti-bedsore)", th: "ที่นอนลมป้องกันแผลกดทับ" },
    "移位機": { vi: "Máy nâng người", en: "Patient Lift (Hoist)", id: "Mesin pengangkat pasien (Hoist)", fil: "Patient lift", th: "เครื่องยกย้ายตัวผู้ป่วย" },
    "便盆椅": { vi: "Ghế bô", en: "Commode Chair", id: "Kursi buang air (Commode)", fil: "Commode chair", th: "เก้าอี้นั่งถ่าย" },
    "洗澡椅": { vi: "Ghế tắm", en: "Shower Chair", id: "Kursi mandi", fil: "Shower chair", th: "เก้าอี้อาบน้ำ" },
    "助聽器": { vi: "Máy trợ thính", en: "Hearing Aid", id: "Alat bantu dengar", fil: "Hearing aid", th: "เครื่องช่วยฟัง" },
    "伐步車": { vi: "Xe tập đi", en: "Rollator Walker", id: "Alat bantu jalan (Rollator)", fil: "Rollator walker", th: "รถเข็นช่วยเดิน" },
    "助步車": { vi: "Xe tập đi", en: "Rollator Walker", id: "Alat bantu jalan (Rollator)", fil: "Rollator walker", th: "รถเข็นช่วยเดิน" },
    "假牙": { vi: "Răng giả", en: "Dentures", id: "Gigi palsu", fil: "Pustiso", th: "ฟันปลอม" },
    "義齒": { vi: "Răng giả", en: "Dentures", id: "Gigi tiruan", fil: "Pustiso", th: "ฟันปลอม" },
    "移位滑板": { vi: "Tấm trượt di chuyển", en: "Slide Transfer Board", id: "Papan transfer (Slide board)", fil: "Transfer board", th: "แผ่นเลื่อนย้ายตัว" },
    "移位腰帶": { vi: "Đai chuyển người", en: "Transfer Gait Belt", id: "Sabuk transfer", fil: "Gait belt", th: "เข็มขัดช่วยพยุงเดิน" },
    "約束帶": { vi: "Dây đai cố định", en: "Restraint Belt", id: "Tali pengikat (Restraint)", fil: "Restraint belt", th: "สายรัดตัว" },
    "氧氣機": { vi: "Máy tạo oxy", en: "Oxygen Concentrator", id: "Konsentrator oksigen", fil: "Oxygen concentrator", th: "เครื่องผลิตออกซิเจน" },
    "抽痰機": { vi: "Máy hút đờm", en: "Suction Machine", id: "Mesin suction", fil: "Suction machine", th: "เครื่องดูดเสมหะ" },
    "減壓坐墊": { vi: "Đệm ngồi giảm áp lực", en: "Pressure Relief Cushion", id: "Bantal anti-luka tekan", fil: "Pressure relief cushion", th: "เบาะรองนั่งลดแรงกดทับ" },
    "無使用輔具": { vi: "Không sử dụng", en: "No Assistive Devices", id: "Tidak menggunakan alat bantu", fil: "Walang gamit na pantulong", th: "ไม่ใช้อุปกรณ์ช่วย" }
  },

  // 移位能力
  transferAbility: {
    "可自行走動": { vi: "Tự đi lại được", en: "Walks Independently", id: "Bisa jalan mandiri", fil: "Kayang lumakad mag-isa", th: "เดินได้เอง" },
    "獨立走動": { vi: "Tự đi lại được", en: "Walks Independently", id: "Bisa jalan mandiri", fil: "Kayang lumakad mag-isa", th: "เดินได้เอง" },
    "需扶持": { vi: "Cần người đỡ", en: "Needs Assistance Walking", id: "Perlu dituntun / dipegang", fil: "Kailangan ng akay", th: "ต้องมีคนพยุง" },
    "需協助上下床": { vi: "Cần hỗ trợ lên xuống giường", en: "Needs Bed Transfer Assistance", id: "Perlu bantu bangun dari kasur", fil: "Tulong sa pag-akyat/baba sa kama", th: "ช่วยพยุงขึ้นลงเตียง" },
    "需2人協助": { vi: "Cần 2 người hỗ trợ", en: "Needs 2-Person Transfer", id: "Perlu 2 orang untuk mobilisasi", fil: "Kailangan ng 2 tao sa paglipat", th: "ต้องใช้ 2 คนช่วยยกย้าย" },
    "完全臥床": { vi: "Nằm liệt giường hoàn toàn", en: "Total Bedridden", id: "Tirah baring total", fil: "Nakahiga sa kama nang permanente", th: "นอนติดเตียงตลอดเวลา" },
    "絕對臥床": { vi: "Nằm bất động tuyệt đối trên giường", en: "Strict Bed Rest (Absolute Bedridden)", id: "Tirah baring mutlak", fil: "Ganap na nakahiga sa kama", th: "นอนติดเตียงเด็ดขาด" },
    "臥床": { vi: "Nằm liệt giường hoàn toàn", en: "Bedridden", id: "Tirah baring total", fil: "Nakahiga sa kama nang permanente", th: "นอนติดเตียงตลอดเวลา" },
    "需使用移位機": { vi: "Cần dùng máy nâng người", en: "Needs Patient Hoist", id: "Perlu alat angkat pasien", fil: "Kailangan ng patient hoist", th: "ต้องใช้เครื่องยกตัว" },
    "需特製推車": { vi: "Cần xe đẩy chuyên dụng", en: "Needs Custom Stroller/Cart", id: "Perlu kereta dorong khusus", fil: "Kailangan ng espesyal na stroller", th: "ต้องใช้รถเข็นเฉพาะ" },
    "只能短暫坐起": { vi: "Chỉ ngồi dậy được thời gian ngắn", en: "Can Only Sit Briefly", id: "Hanya bisa duduk sebentar", fil: "Kayang umupo nang panandalian lamang", th: "นั่งได้ชั่วครู่เท่านั้น" }
  },

  // 排泄照護
  elimination: {
    "自行如廁": { vi: "Tự đi vệ sinh", en: "Independent Toilet Use", id: "Buang air mandiri ke toilet", fil: "Pumupunta sa banyo mag-isa", th: "เข้าห้องน้ำได้เอง" },
    "尿布": { vi: "Dùng tã giấy", en: "Adult Diaper", id: "Pakai popok (Diapers)", fil: "Gumagamit ng lampin / diaper", th: "ใช้ผ้าอ้อมผู้ใหญ่" },
    "使用尿布": { vi: "Dùng tã giấy", en: "Adult Diaper", id: "Pakai popok (Diapers)", fil: "Gumagamit ng lampin / diaper", th: "ใช้ผ้าอ้อมผู้ใหญ่" },
    "尿褲": { vi: "Dùng quần tã", en: "Pull-up Incontinence Pants", id: "Pakai popok celana (Pull-ups)", fil: "Gumagamit ng pull-up diaper", th: "ใช้กางเกงผ้าอ้อม" },
    "使用尿褲": { vi: "Dùng quần tã", en: "Pull-up Incontinence Pants", id: "Pakai popok celana (Pull-ups)", fil: "Gumagamit ng pull-up diaper", th: "ใช้กางเกงผ้าอ้อม" },
    "留置導尿管": { vi: "Đặt ống thông tiểu lưu (Foley)", en: "Indwelling Foley Catheter", id: "Pakai kateter urine (Foley)", fil: "May nakakabit na Foley catheter", th: "คาสายสวนปัสสาวะ" },
    "導尿管": { vi: "Đặt ống thông tiểu lưu (Foley)", en: "Foley Catheter", id: "Pakai kateter urine", fil: "May Foley catheter", th: "คาสายสวนปัสสาวะ" },
    "便盆椅": { vi: "Ghế bô", en: "Commode Chair", id: "Kursi buang air (Commode)", fil: "Commode chair", th: "เก้าอี้นั่งถ่าย" },
    "使用便盆椅": { vi: "Ghế bô", en: "Commode Chair", id: "Kursi buang air (Commode)", fil: "Commode chair", th: "เก้าอี้นั่งถ่าย" },
    "便盆": { vi: "Dùng bô dẹt tại giường", en: "Bedpan Use", id: "Pakai pispot sodok (Bedpan)", fil: "Gumagamit ng bedpan", th: "ใช้หม้อนอนบนเตียง" },
    "便盆使用": { vi: "Dùng bô dẹt tại giường", en: "Bedpan Use", id: "Pakai pispot sodok (Bedpan)", fil: "Gumagamit ng bedpan", th: "ใช้หม้อนอนบนเตียง" },
    "尿壺": { vi: "Dùng bô tiểu (Urinal)", en: "Urinal Bottle Use", id: "Pakai urinal botol", fil: "Gumagamit ng urinal", th: "ใช้กระบอกปัสสาวะ" },
    "尿壺使用": { vi: "Dùng bô tiểu (Urinal)", en: "Urinal Bottle Use", id: "Pakai urinal botol", fil: "Gumagamit ng urinal", th: "ใช้กระบอกปัสสาวะ" },
    "腸造口照護": { vi: "Mở hậu môn nhân tạo (Stoma)", en: "Colostomy / Stoma Care", id: "Memiliki stoma / kolostomi", fil: "May colostomy / stoma", th: "มีทวารเทียมที่หน้าท้อง" },
    "腸造口": { vi: "Mở hậu môn nhân tạo (Stoma)", en: "Stoma Care", id: "Memiliki stoma / kolostomi", fil: "May colostomy / stoma", th: "มีทวารเทียมที่หน้าท้อง" },
    "需協助更換": { vi: "Cần hỗ trợ thay tã", en: "Needs Changing Assistance", id: "Perlu dibantu ganti popok", fil: "Kailangang tulungan magpalit", th: "ต้องการคนช่วยเปลี่ยนผ้าอ้อม" },
    "定時如廁": { vi: "Đi vệ sinh định kỳ", en: "Scheduled Toileting", id: "Jadwal buang air teratur", fil: "Naka-iskedyul na pag-ihi/dumi", th: "พาเข้าห้องน้ำตามเวลา" }
  },

  // 重要注意事項
  precautions: {
    "小心跌倒": { vi: "Phòng ngừa té ngã", en: "Fall Risk / Prevent Falls", id: "Waspada jatuh (Resiko tinggi jatuh)", fil: "Mag-ingat sa pagkahulog (Fall risk)", th: "ระวังการหกล้มพลัดตก" },
    "防跌倒": { vi: "Phòng ngừa té ngã", en: "Fall Prevention", id: "Pencegahan jatuh", fil: "Iwasan ang pagkahulog", th: "ป้องกันการหกล้ม" },
    "翻身擺位": { vi: "Trở mình, thay đổi tư thế", en: "Repositioning & Turning", id: "Ubah posisi baring & miring", fil: "Pag-iiba ng posisyon", th: "พลิกตัวจัดท่านอน" },
    "翻身 (每2小時)": { vi: "Trở mình định kỳ (mỗi 2 giờ)", en: "Turn & Reposition (Every 2h)", id: "Miring kanan/kiri tiap 2 jam", fil: "Iposisyon bawat 2 oras (Turn every 2h)", th: "พลิกตัวทุก 2 ชั่วโมง" },
    "每2小時翻身": { vi: "Trở mình định kỳ (mỗi 2 giờ)", en: "Turn & Reposition (Every 2h)", id: "Miring kanan/kiri tiap 2 jam", fil: "Iposisyon bawat 2 oras", th: "พลิกตัวทุก 2 ชั่วโมง" },
    "拍背排痰": { vi: "Vỗ lưng bài đờm", en: "Chest Percussion / Sputum Clearance", id: "Tepuk punggung keluarkan dahak", fil: "Tapikin ang likod para sa plema", th: "เคาะปอดขับเสมหะ" },
    "蒸氣吸入": { vi: "Khí dung (xông họng)", en: "Nebulizer Inhalation Therapy", id: "Nebulizer (Terapi uap)", fil: "Nebulizer / Suob", th: "พ่นยาขยายหลอดลม" },
    "血糖監測": { vi: "Theo dõi đường huyết", en: "Blood Glucose Monitoring", id: "Cek gula darah rutin", fil: "Bantayan ang asukal sa dugo", th: "ตรวจระดับน้ำตาลในเลือด" },
    "拒藥傾向": { vi: "Hay từ chối uống thuốc", en: "Medication Refusal Tendency", id: "Cenderung menolak minum obat", fil: "Tinatanggihan ang gamot", th: "มีแนวโน้มปฏิเสธยา" },
    "藏藥行為": { vi: "Có hành vi giấu thuốc", en: "Hiding Medication Behavior", id: "Sering menyembunyikan obat", fil: "Nagtatago ng gamot", th: "มีพฤติกรรมแอบซ่อนยา" },
    "安寧療護": { vi: "Chăm sóc giảm nhẹ (Hospice)", en: "Palliative / Hospice Care", id: "Perawatan paliatif / hospice", fil: "Palliative care", th: "การดูแลแบบประคับประคอง" },
    "嗆咳風險": { vi: "Nguy cơ sặc khi nuốt", en: "Choking / Aspiration Risk", id: "Bahaya tersedak saat makan/minum", fil: "Panganib na mabilaukan", th: "เสี่ยงต่อการสำลัก" },
    "易嗆咳": { vi: "Dễ bị sặc khi nuốt", en: "Prone to Choking", id: "Mudah tersedak", fil: "Madaling mabilaukan", th: "สำลักง่าย" },
    "防嗆咳": { vi: "Phòng ngừa sặc khi nuốt", en: "Prevent Aspiration / Choking", id: "Pencegahan tersedak", fil: "Iwasan ang mabilaukan", th: "ป้องกันการสำลัก" },
    "左手禁治療": { vi: "Không điều trị / can thiệp tay trái", en: "No Treatment Left Arm", id: "Dilarang tindakan tangan kiri", fil: "Bawal gamutin sa kaliwang braso", th: "ห้ามทำการรักษาแขนซ้าย" },
    "右手禁治療": { vi: "Không điều trị / can thiệp tay phải", en: "No Treatment Right Arm", id: "Dilarang tindakan tangan kanan", fil: "Bawal gamutin sa kanang braso", th: "ห้ามทำการรักษาแขนขวา" },
    "左手禁止治療": { vi: "Không điều trị / can thiệp tay trái", en: "No Treatment Left Arm", id: "Dilarang tindakan tangan kiri", fil: "Bawal gamutin sa kaliwang braso", th: "ห้ามทำการรักษาแขนซ้าย" },
    "右手禁止治療": { vi: "Không điều trị / can thiệp tay phải", en: "No Treatment Right Arm", id: "Dilarang tindakan tangan kanan", fil: "Bawal gamutin sa kanang braso", th: "ห้ามทำการรักษาแขนขวา" },
    "左手禁止量血壓": { vi: "Không điều trị / can thiệp tay trái", en: "No Treatment Left Arm", id: "Dilarang tindakan tangan kiri", fil: "Bawal gamutin sa kaliwang braso", th: "ห้ามทำการรักษาแขนซ้าย" },
    "右手禁止量血壓": { vi: "Không điều trị / can thiệp tay phải", en: "No Treatment Right Arm", id: "Dilarang tindakan tangan kanan", fil: "Bawal gamutin sa kanang braso", th: "ห้ามทำการรักษาแขนขวา" },
    "左腳禁扎針": { vi: "Không tiêm kim chân trái", en: "No Needle / IV Left Leg", id: "Dilarang suntik kaki kiri", fil: "Bawal tusukan sa kaliwang binti", th: "ห้ามฉีดยา/เจาะขาซ้าย" },
    "右腳禁扎針": { vi: "Không tiêm kim chân phải", en: "No Needle / IV Right Leg", id: "Dilarang suntik kaki kanan", fil: "Bawal tusukan sa kanang binti", th: "ห้ามฉีดยา/เจาะขาขวา" },
    "左手禁扎針": { vi: "Không tiêm kim tay trái", en: "No Needle / IV Left Arm", id: "Dilarang suntik tangan kiri", fil: "Bawal tusukan sa kaliwang braso", th: "ห้ามฉีดยา/เจาะแขนซ้าย" },
    "右手禁扎針": { vi: "Không tiêm kim tay phải", en: "No Needle / IV Right Arm", id: "Dilarang suntik tangan kanan", fil: "Bawal tusukan sa kanang braso", th: "ห้ามฉีดยา/เจาะแขนขวา" },
    "假牙保管": { vi: "Bảo quản răng giả", en: "Dentures Safe Storage", id: "Simpan gigi palsu", fil: "Ingatan ang pustiso", th: "เก็บรักษาฟันปลอม" },
    "義齒保管": { vi: "Bảo quản răng giả", en: "Dentures Safe Storage", id: "Simpan gigi tiruan", fil: "Ingatan ang pustiso", th: "เก็บรักษาฟันปลอม" },
    "助聽器保管": { vi: "Bảo quản máy trợ thính", en: "Hearing Aid Safe Storage", id: "Simpan alat bantu dengar", fil: "Ingatan ang hearing aid", th: "เก็บรักษาเครื่องช่วยฟัง" },
    "禁食": { vi: "Nhịn ăn uống (NPO)", en: "NPO (Nothing by Mouth)", id: "Puasa makan dan minum (NPO)", fil: "Bawal kumain at uminom (NPO)", th: "งดน้ำและอาหาร" },
    "傷口照護": { vi: "Chăm sóc vết thương", en: "Wound Care & Dressing", id: "Perawatan luka", fil: "Pangangalaga sa sugat", th: "ทำแผล" },
    "壓傷高風險": { vi: "Nguy cơ loét tì đè cao", en: "High Risk of Pressure Injury", id: "Risiko tinggi luka tekan", fil: "Mataas na panganib ng sugat sa kama", th: "มีความเสี่ยงสูงต่อแผลกดทับ" },
    "皮膚完整性": { vi: "Nguy cơ loét tì đè cao", en: "High Risk of Pressure Injury", id: "Risiko tinggi luka tekan", fil: "Mataas na panganib ng sugat sa kama", th: "มีความเสี่ยงสูงต่อแผลกดทับ" },
    "皮膚完整性注意": { vi: "Nguy cơ loét tì đè cao", en: "High Risk of Pressure Injury", id: "Risiko tinggi luka tekan", fil: "Mataas na panganib ng sugat sa kama", th: "มีความเสี่ยงสูงต่อแผลกดทับ" },
    "防自拔管路": { vi: "Đề phòng tự rút ống thông", en: "Prevent Tube Self-Extubation", id: "Waspada pasien mencabut selang", fil: "Ingatan na huwag hilahin ang tubo", th: "ระวังดึงสายยางออกเอง" },
    "補充水分": { vi: "Chú ý nhắc uống nước", en: "Encourage Hydration", id: "Ingatkan cukup minum air", fil: "Paalalahanan uminom ng tubig", th: "กระตุ้นการดื่มน้ำ" },
    "補充水分注意": { vi: "Chú ý nhắc uống nước", en: "Encourage Hydration", id: "Ingatkan cukup minum air", fil: "Paalalahanan uminom ng tubig", th: "กระตุ้นการดื่มน้ำ" },
    "限制水分": { vi: "Hạn chế uống nước", en: "Fluid Restriction Alert", id: "Batasi asupan air", fil: "Limitahan ang tubig", th: "ควบคุมการดื่มน้ำ" },
    "限制水分注意": { vi: "Hạn chế uống nước", en: "Fluid Restriction Alert", id: "Batasi asupan air", fil: "Limitahan ang tubig", th: "ควบคุมการดื่มน้ำ" },
    "情緒關懷": { vi: "Chăm sóc và hỗ trợ cảm xúc", en: "Emotional Care & Support", id: "Dukungan & Perawatan Emosional", fil: "Pag-aaruga sa Emosyon", th: "การดูแลและประคับประคองอารมณ์" },
    "癲癇防護": { vi: "Phòng ngừa co giật (động kinh)", en: "Seizure Precautions", id: "Pencegahan kejang (Epilepsi)", fil: "Pag-iingat sa pangingisay", th: "ระวังอาการชัก" },
    "約束安全": { vi: "An toàn khi cố định / kiềm chế", en: "Restraint Care & Safety", id: "Keselamatan fiksasi / restraint", fil: "Kaligtasan sa paggapos", th: "ความปลอดภัยการผูกยึด" },
    "約束照護注意": { vi: "Lưu ý chăm sóc đai cố định", en: "Restraint Care & Safety", id: "Perhatian perawatan fiksasi", fil: "Pag-iingat sa restraint", th: "การดูแลผู้ป่วยที่ถูกผูกมัด" }
  }
};

/**
 * 長照常用常見別名與英文縮寫速查字典 (Alias Dictionary)
 */
const CARE_ALIASES = {
  // 英文醫療縮寫
  'HTN': '高血壓',
  'DM': '糖尿病',
  'CVA': '腦中風',
  'STROKE': '腦中風',
  'CAD': '冠心症',
  'CHF': '心衰竭',
  'CKD': '慢性腎臟病',
  'COPD': '慢性阻塞性肺病',
  'GERD': '胃食道逆流',
  'BPH': '攝護腺肥大',
  'UTI': '泌尿道感染',
  'AMI': '心肌梗塞',
  'AFIB': '心房顫動',
  'AF': '心房顫動',
  'GOUT': '痛風',
  'ASTHMA': '氣喘',
  'CANCER': '癌症',
  'NPO': '禁食',
  'FOLEY': '留置導尿管',
  'NG': '鼻胃管灌食',
  'PEG': '胃造口灌食',

  // 中文常見簡稱與別名
  '冠心病': '冠心症',
  '腦梗塞': '腦中風',
  '心臟衰竭': '心衰竭',
  '三高': '高血壓',
  '高血脂症': '高血脂',
  '骨鬆': '骨質疏鬆',
  '關節退化': '退化性關節炎',
  '帕金森': '帕金森氏症',
  '巴金森': '帕金森氏症',
  '巴金森氏症': '帕金森氏症',
  '失智': '失智症',
  '老人失智': '失智症',
  '中風': '腦中風',
  '尿道感染': '泌尿道感染',
  '腎衰竭': '慢性腎臟病',
  '換藥': '傷口照護',
  '傷口護理': '傷口照護',
  '皮膚注意': '壓傷高風險',
  '皮膚完整性注意': '壓傷高風險',
  '皮膚完整性': '壓傷高風險',
  '壓傷高危險': '壓傷高風險',
  '壓瘡高危險': '壓傷高風險',
  '壓傷注意': '壓傷高風險',
  '特製輪椅': '輪椅',
  '特製輪椅使用': '輪椅',
  '電動輪椅': '輪椅',
  '防拔管': '防自拔管路',
  '防跌倒': '小心跌倒',
  '補充水分注意': '補充水分',
  '限制水分注意': '限制水分',
  '約束照護注意': '約束安全',
  '約束注意': '約束安全',
  '情緒支持': '情緒關懷',
  '心理支持': '情緒關懷',
  '情緒安撫': '情緒關懷',
  '情緒照護': '情緒關懷',
  '翻身': '翻身擺位',
  '翻身(2h)': '翻身擺位',
  '翻身 (2h)': '翻身擺位',
  '翻身 (每2小時)': '翻身擺位',
  '左手禁量血壓': '左手禁治療',
  '右手禁量血壓': '右手禁治療',
  '左手禁血壓': '左手禁治療',
  '右手禁血壓': '右手禁治療',
  '左手禁止治療': '左手禁治療',
  '右手禁止治療': '右手禁治療',
  '左手禁止量血壓': '左手禁治療',
  '右手禁止量血壓': '右手禁治療',
  '左側禁治療': '左手禁治療',
  '右側禁治療': '右手禁治療',
  '左側禁止治療': '左手禁治療',
  '右側禁止治療': '右手禁治療',
  '皮膚注意': '皮膚完整性注意',
  '補充水分': '補充水分注意',
  '輪椅使用': '輪椅',
  '換尿布': '需協助更換',
  '包尿布': '使用尿布',
  '穿尿褲': '使用尿褲',
  '吃菜粥': '攪菜粥',
  '碎食': '碎食飲食',
  '軟質': '軟質飲食',
  '軟食': '軟質飲食',
  '灌食': '鼻胃管灌食'
};

// 完整漢越音字典 (台灣常見長照百家姓與高頻姓名用字，350+字)
const HAN_VIET_DICT = {
  "鏗": "Khang", "煒": "Vĩ", "瑄": "Tuyên", "筑": "Trúc", "綺": "Khởi",
  "曜": "Diệu", "宸": "Thần", "要": "Yếu", "鈞": "Quân", "鈺": "Ngọc",
  "鑫": "Hâm", "詠": "Vịnh", "奕": "Dịch", "宥": "Hựu", "佑": "Hữu",
  "祐": "Hữu", "叡": "Duệ", "喆": "Triết", "愷": "Khải", "璿": "Tuyền",
  "瑋": "Vĩ", "珉": "Mân", "妍": "Nghiên", "希": "Hy", "霏": "Phi",
  "霓": "Nghê", "馳": "Trì", "駿": "Tuấn", "逸": "Dật", "楷": "Giai",
  "倫": "Luân", "晟": "Thịnh", "璟": "Cảnh", "瑀": "Vũ", "璨": "Sán",
  "爍": "Thước", "翊": "Dực", "靖": "Tĩnh", "霆": "Đình", "芊": "Thiên",
  "筠": "Quân", "筱": "Tiểu", "媗": "Huyên", "嫈": "Oanh", "嫺": "Nhàn",
  "嫻": "Nhàn", "嫣": "Yên", "穎": "Dĩnh", "歆": "Hâm", "昕": "Hân",
  "昀": "Vân", "晞": "Hy", "曄": "Diệp", "燁": "Diệp", "昊": "Hạo",
  "昂": "Ngang", "昇": "Thăng", "旻": "Mân", "昆": "Côn", "昶": "Sưởng",
  "梵": "Phạn", "柱": "Trụ", "梓": "Tử", "杰": "Kiệt", "植": "Thực",
  "槐": "Hòe", "榆": "Du", "榛": "Trăn", "樞": "Xu", "模": "Mô",
  "樣": "Dạng", "機": "Cơ", "橫": "Hoành", "檀": "Đàn", "櫻": "Anh",
  "陳": "Trần", "林": "Lâm", "黃": "Hoàng", "張": "Trương", "李": "Lý",
  "王": "Vương", "吳": "Ngô", "劉": "Lưu", "蔡": "Thái", "楊": "Dương",
  "許": "Hứa", "鄭": "Trịnh", "謝": "Tạ", "洪": "Hồng", "郭": "Quách",
  "邱": "Khâu", "曾": "Tăng", "廖": "Liêu", "賴": "Lại", "周": "Chu",
  "徐": "Từ", "蘇": "Tô", "葉": "Diệp", "莊": "Trang", "呂": "Lữ",
  "江": "Giang", "何": "Hà", "蕭": "Tiêu", "羅": "La", "高": "Cao",
  "潘": "Phan", "簡": "Giản", "朱": "Chu", "彭": "Bành", "游": "Du",
  "詹": "Chiêm", "胡": "Hồ", "施": "Thi", "沈": "Thẩm", "柯": "Kha",
  "盧": "Lư", "余": "Dư", "翁": "Ông", "魏": "Ngụy", "孫": "Tôn",
  "戴": "Đái", "范": "Phạm", "方": "Phương", "鄧": "Đặng", "杜": "Đỗ",
  "阮": "Nguyễn", "石": "Thạch", "姚": "Dao", "邵": "Thiệu", "康": "Khang",
  "武": "Võ", "錢": "Tiền", "湯": "Thang", "嚴": "Nghiêm", "金": "Kim",
  "白": "Bạch", "陸": "Lục", "包": "Bao", "童": "Đồng", "鄒": "Trâu",
  "巫": "Vu", "鐘": "Chung", "鍾": "Chung", "卓": "Trác", "顏": "Nhan",
  "連": "Liên", "丁": "Đinh", "薛": "Tiết", "馬": "Mã", "董": "Đổng",
  "唐": "Đường", "馮": "Phùng", "程": "Trình", "曹": "Tào", "袁": "Viên",
  "雄": "Hùng", "慧": "Tuệ", "晶": "Tinh", "美": "Mỹ", "華": "Hoa",
  "榮": "Vinh", "富": "Phú", "貴": "Quý", "春": "Xuân", "夏": "Hạ",
  "秋": "Thu", "冬": "Đông", "木": "Mộc", "水": "Thủy", "火": "Hỏa",
  "土": "Thổ", "文": "Văn", "明": "Minh", "德": "Đức", "仁": "Nhân",
  "義": "Nghĩa", "禮": "Lễ", "智": "Trí", "信": "Tín", "忠": "Trung",
  "孝": "Hiếu", "國": "Quốc", "安": "An", "平": "Bình", "和": "Hòa",
  "順": "Thuận", "發": "Phát", "財": "Tài", "興": "Hưng", "旺": "Vượng",
  "盛": "Thịnh", "茂": "Mậu", "良": "Lương", "友": "Hữu", "成": "Thành",
  "功": "Công", "達": "Đạt", "進": "Tiến", "步": "Bộ", "超": "Siêu",
  "群": "Quần", "俊": "Tuấn", "傑": "Kiệt", "英": "Anh", "豪": "Hào",
  "勇": "Dũng", "強": "Cường", "健": "Kiện", "大": "Đại", "小": "Tiểu",
  "寶": "Bảo", "珠": "Châu", "玉": "Ngọc", "芳": "Phương", "芬": "Phân",
  "花": "Hoa", "蘭": "Lan", "梅": "Mai", "秀": "Tú", "麗": "Lệ",
  "雅": "Nhã", "清": "Thanh", "潔": "Khiết", "素": "Tố", "真": "Chân",
  "貞": "Trinh", "淑": "Thục", "惠": "Huệ", "娟": "Quyên", "娥": "Nga",
  "妹": "Muội", "鳳": "Phượng", "凰": "Hoàng", "松": "Tùng", "柏": "Bách",
  "雲": "Vân", "海": "Hải", "山": "Sơn", "志": "Chí", "婷": "Đình",
  "冠": "Quán", "樺": "Hoa", "凱": "Khải", "宇": "Vũ", "翔": "Tường",
  "玲": "Linh", "萍": "Bình", "珍": "Trân", "琴": "Cầm", "琳": "Lâm",
  "欣": "Hân", "怡": "Di", "萱": "Huyên", "涵": "Hàm", "晴": "Tình",
  "琪": "Kỳ", "佳": "Giai", "佩": "Bội", "珊": "San", "雯": "Văn",
  "銘": "Minh", "宏": "Hoành", "偉": "Vĩ", "宗": "Tông", "家": "Gia",
  "建": "Kiến", "廷": "Đình", "庭": "Đình", "承": "Thừa", "哲": "Triết",
  "瑞": "Thụy", "睿": "Duệ", "皓": "Hạo", "瀚": "Hãn", "辰": "Thần",
  "昱": "Dục", "晨": "Thần", "霖": "Lâm", "毅": "Nghị", "捷": "Tiệp",
  "謙": "Khiêm", "遠": "Viễn", "慶": "Khánh", "豐": "Phong", "泰": "Thái",
  "銳": "Nhuệ", "鋒": "Phong", "鎮": "Trấn", "銓": "Thuyên", "棠": "Đường",
  "楓": "Phong", "榕": "Dung", "桂": "Quế", "桐": "Đồng", "樟": "Chương",
  "沛": "Phái", "治": "Trị", "泳": "Vịnh", "浩": "Hạo", "淳": "Thuần",
  "淵": "Uyên", "濤": "Đào", "鴻": "Hồng", "澎": "Bành", "潮": "Triều",
  "澤": "Trạch", "濟": "Tế", "潤": "Nhuận", "炳": "Bỉnh", "炯": "Quýnh",
  "炫": "Huyễn", "烽": "Phong", "煥": "Hoán", "煜": "Dục", "熙": "Hi",
  "燃": "Nhiên", "培": "Bồi", "均": "Quân", "坤": "Khôn", "城": "Thành",
  "基": "Cơ", "堂": "Đường", "堯": "Nghiêu", "增": "Tăng", "壇": "Đàn",
  "壁": "Bích", "壕": "Hào", "霞": "Hà", "瓊": "Quỳnh", "雪": "Tuyết",
  "蓮": "Liên", "月": "Nguyệt", "愛": "Ái", "心": "Tâm", "慈": "Từ",
  "光": "Quang", "生": "Sinh", "福": "Phúc", "壽": "Thọ", "阿": "A",
  "來": "Lai", "添": "Thiêm", "吉": "Cát", "祥": "Tường", "如": "Như",
  "意": "Ý", "樹": "Thụ", "根": "Căn", "通": "Thông", "竹": "Trúc",
  "菊": "Cúc", "桃": "Đào", "枝": "Chi", "滿": "Mãn", "銀": "Ngân",
  "嬌": "Kiều", "好": "Hảo", "姐": "Tỷ", "伯": "Bá", "仲": "Trọng",
  "叔": "Thúc", "季": "Quý", "長": "Trường", "定": "Định", "保": "Bảo",
  "泉": "Tuyền", "河": "Hà", "川": "Xuyên", "天": "Thiên", "地": "Địa",
  "乾": "Càn", "元": "Nguyên", "亨": "Hanh", "利": "Lợi", "顯": "Hiển",
  "揚": "Dương", "輝": "Huy", "耀": "Diệu", "祖": "Tổ", "朝": "Triều",
  "邦": "Bang", "斌": "Bân", "憲": "Hiến", "政": "Chính", "中": "Trung",
  "正": "Chính", "錦": "Cẩm", "繡": "Tú", "瑟": "Sắt", "碧": "Bích",
  "彩": "Thải", "翠": "Thúy", "仙": "Tiên", "妙": "Diệu", "香": "Hương",
  "霜": "Sương", "露": "Lộ", "溫": "Ôn", "崔": "Thôi", "賈": "Giả",
  "路": "Lộ", "毛": "Mao", "嬤": "Ma", "公": "Công", "婆": "Bà",
  "爺": "Gia", "爸": "Ba", "媽": "Ma", "哥": "Ca", "弟": "Đệ",
  "罔": "Võng", "市": "Thị", "腰": "Yêu", "招": "Chiêu", "賜": "Tứ",
  "祿": "Lộc", "欽": "Khâm", "勝": "Thắng", "男": "Nam", "標": "Tiêu",
  "棟": "Đống", "樑": "Lương", "森": "Sâm", "彬": "Bân", "星": "Tinh",
  "湖": "Hồ", "池": "Trì", "潭": "Đàm", "洲": "Châu", "隆": "Long",
  "昌": "Xương", "喜": "Hỷ", "日": "Nhật", "島": "Đảo", "岩": "Nham",
  "峰": "Phong", "嶺": "Lĩnh", "崗": "Cương", "岳": "Nhạc", "鐵": "Thiết",
  "銅": "Đồng", "鋼": "Cương", "錫": "Tích", "鑑": "Giám", "鑽": "Toán",
  "環": "Hoàn", "瑛": "Anh", "瑜": "Du", "瑤": "Dao", "瑾": "Cẩn",
  "璇": "Tuyền", "瑚": "Hồ", "瓏": "Lung", "荷": "Hà", "芝": "Chi",
  "草": "Thảo", "敏": "Mẫn", "靜": "Tĩnh", "端": "Đoan", "賢": "Hiền",
  "善": "Thiện", "情": "Tình", "恩": "Ân", "念": "Niệm", "思": "Tư",
  "想": "Tưởng", "懷": "Hoài", "憶": "Ức", "願": "Nguyện", "寬": "Khoan",
  "厚": "Hậu", "誠": "Thành", "樸": "Phác", "純": "Thuần", "實": "Thực",
  "遜": "Tốn", "謹": "Cẩn", "慎": "Thận", "恭": "Cung", "敬": "Kính",
  "剛": "Cương", "猛": "Mãnh", "烈": "Liệt", "彥": "Ngạn", "儒": "Nho",
  "學": "Học", "書": "Thư", "章": "Chương", "翰": "Hàn", "墨": "Mặc",
  "研": "Nghiên", "究": "Cứu", "創": "Sáng", "造": "Tạo", "立": "Lập",
  "業": "Nghiệp", "開": "Khai", "展": "Triển", "拓": "Thác", "升": "Thăng",
  "騰": "Đằng", "飛": "Phi", "鵬": "Bằng", "鶴": "Hạc", "鷹": "Ưng",
  "燕": "Yến", "雀": "Tước", "虎": "Hổ", "豹": "Báo", "龍": "Long",
  "麟": "Lân", "龜": "Quy", "青": "Thanh", "綠": "Lục", "紅": "Hồng",
  "赤": "Xích", "黑": "Hắc", "玄": "Huyền", "紫": "Tử", "丹": "Đan",
  "彤": "Đồng", "絢": "Huyễn", "燦": "Sán", "爛": "Lạn", "煌": "Hoàng",
  "照": "Chiếu", "暉": "Huy", "曦": "Hi", "旭": "Húc", "東": "Đông",
  "西": "Tây", "南": "Nam", "北": "Bắc", "上": "Thượng", "下": "Hạ",
  "前": "Tiền", "後": "Hậu", "左": "Tả", "右": "Hữu", "一": "Nhất",
  "二": "Nhị", "三": "Tam", "四": "Tứ", "五": "Ngũ", "六": "Lục",
  "七": "Thất", "八": "Bát", "九": "Cửu", "十": "Thập", "百": "Bách",
  "千": "Thiên", "萬": "Vạn", "億": "Ức", "兆": "Triệu", "初": "Sơ",
  "始": "Thủy", "終": "Chung", "永": "Vĩnh", "久": "Cửu", "恆": "Hằng",
  "常": "Thường", "寧": "Ninh", "睦": "Mục", "朋": "Bằng", "賓": "Tân",
  "客": "Khách", "鄰": "Lân", "里": "Lý", "鄉": "Hương", "村": "Thôn",
  "州": "Châu", "省": "Tỉnh", "縣": "Huyện", "府": "Phủ", "室": "Thất",
  "門": "Môn", "戶": "Hộ", "居": "Cư", "宅": "Trạch", "園": "Viên",
  "院": "Viện", "樓": "Lâu", "閣": "Các", "亭": "Đình", "榭": "Tạ",
  "臺": "Đài", "台": "Đài", "源": "Nguyên", "溪": "Khê", "澗": "Giản",
  "瀧": "Lung", "浪": "Lãng", "波": "Ba", "瀾": "Lan", "洋": "Dương",
  "滄": "Thương", "溟": "Minh", "浮": "Phù", "泛": "Phiếm", "深": "Sâm",
  "澈": "Triệt", "澄": "Trừng", "淨": "Tịnh", "洗": "Tẩy", "滌": "Địch",
  "沐": "Mộc", "浴": "Dục", "灌": "Quán", "溉": "Cái", "溢": "Dật",
  "滔": "Thao", "湧": "Dũng", "湃": "Bái", "汐": "Tịch", "汛": "Tấn",
  "津": "Tân", "渡": "Độ", "舟": "Chu", "船": "Thuyền", "帆": "Phàm",
  "航": "Hàng", "艦": "Hạm", "舵": "Đà", "錨": "Mao", "岸": "Ngạn",
  "港": "Cảng", "灣": "Loan", "浦": "Phổ", "濱": "Tân", "灘": "Than",
  "渚": "Chử", "嶼": "Dữ", "妤": "Dư", "婕": "Tiệp", "茜": "Thiến",
  "薇": "Vi", "蕾": "Lôi", "芷": "Chỉ", "芮": "Nhuế", "芯": "Tâm",
  "茉": "Mạt", "莉": "Lợi", "菲": "Phi", "蓉": "Dung", "蓓": "Bội",
  "蔓": "Mạn", "蓁": "Trăn", "藍": "Lam", "蔚": "Úy", "藝": "Nghệ",
  "芸": "Vân", "芹": "Cần", "茵": "Nhân", "茹": "Như", "莎": "Sa",
  "菁": "Tinh", "菱": "Lăng", "萌": "Manh", "蘿": "La", "蔣": "Tưởng",
  "薄": "Bạc", "藻": "Tảo", "蘆": "Lô", "傅": "Phó", "歐": "Âu",
  "粘": "Niêm", "紀": "Kỷ", "涂": "Đồ", "鄔": "Ổ", "刁": "Điêu",
  "卞": "Biện", "邢": "Hình", "荀": "Tuân", "邰": "Thai", "虞": "Ngu",
  "靳": "Cận", "鮑": "Bào", "閻": "Diêm", "霍": "Hoắc", "繆": "Mậu",
  "譚": "Đàm", "顧": "Cố", "龔": "Cung", "龐": "Bàng", "賀": "Hạ",
  "樊": "Phàn", "焦": "Tiêu", "岑": "Sầm", "莫": "Mạc", "裘": "Cừu",
  "仇": "Cừu", "祝": "Chúc", "辜": "Cô", "駱": "Lạc", "屈": "Khuất",
  "葛": "Cát", "儲": "Trữ", "柴": "Sài", "耿": "Cảnh", "牛": "Ngưu",
  "牧": "Mục", "羊": "Dương", "鹿": "Lộc", "熊": "Hùng", "遲": "Trì",
  "危": "Nguy", "管": "Quản", "冷": "Lãnh", "甘": "Cam", "蒙": "Mông",
  "邊": "Biên", "宮": "Cung", "解": "Giải", "應": "Ứng", "宣": "Tuyên",
  "郁": "Úc", "單": "Đơn", "杭": "Hàng", "諸": "Gia", "鈕": "Nữu",
  "嵇": "Kê", "滑": "Hoạt", "裴": "Bùi", "於": "Ư", "甄": "Chân",
  "麴": "Khúc", "封": "Phong", "羿": "Nghệ", "汲": "Cấp", "邴": "Bính",
  "糜": "Mi", "井": "Tỉnh", "段": "Đoạn", "烏": "Ô", "巴": "Ba",
  "弓": "Cung", "隗": "Ngôi", "谷": "Cốc", "車": "Xa", "侯": "Hầu",
  "宓": "Mật", "蓬": "Bồng", "全": "Toàn", "郗": "Si", "班": "Ban",
  "仰": "Ngưỡng", "伊": "Y", "欒": "Loan", "暴": "Bạo", "郜": "Cáo",
  "符": "Phù", "景": "Cảnh", "束": "Thúc", "幸": "Hạnh", "司": "Tư",
  "韶": "Thiều", "黎": "Lê", "薊": "Kế", "宿": "Túc", "蒲": "Bồ",
  "從": "Tòng", "鄂": "Ngạc", "索": "Tác", "咸": "Hàm", "籍": "Tịch",
  "藺": "Lận", "屠": "Đồ", "喬": "Kiều", "陰": "Âm", "胥": "Tư",
  "能": "Năng", "蒼": "Thương", "雙": "Song", "聞": "Văn", "莘": "Sân",
  "黨": "Đảng", "翟": "Địch", "貢": "Cống", "勞": "Lao", "逄": "Bàng",
  "姬": "Cơ", "申": "Thân", "扶": "Phù", "堵": "Đổ", "冉": "Nhiễm",
  "宰": "Tể", "酈": "Lệ", "雍": "Ung", "郤": "Khích", "璩": "Cừu",
  "桑": "Tang", "濮": "Bộc", "扈": "Hổ", "冀": "Ký", "郟": "Giáp",
  "尚": "Thượng", "農": "Nông", "別": "Biệt", "晏": "Yán", "瞿": "Cù",
  "充": "Sung", "慕": "Mộ", "習": "Tập", "宦": "Hoạn", "艾": "Ngải",
  "魚": "Ngư", "容": "Dung", "向": "Hướng", "古": "Cổ", "易": "Dịch",
  "戈": "Qua", "庾": "Dữ", "暨": "Ký", "衡": "Hành", "都": "Đô",
  "弘": "Hoằng", "匡": "Khuông", "寇": "Khấu", "廣": "Quảng", "闕": "Khuyết",
  "殳": "Thù", "沃": "Ốc", "越": "Việt", "夔": "Quỳ", "師": "Sư",
  "鞏": "Củng", "厙": "Xá", "聶": "Nhiếp", "晁": "Triều", "勾": "Câu",
  "敖": "Ngao", "融": "Dung", "訾": "Tử", "辛": "Tân", "闞": "Hám",
  "那": "Na", "饒": "Nhiêu", "空": "Không", "毋": "Vô", "沙": "Sa",
  "乜": "Kỳ", "養": "Dưỡng", "鞠": "Cúc", "須": "Tu", "巢": "Sào",
  "關": "Quan", "蒯": "Khoái", "相": "Tương", "查": "Tra", "后": "Hậu",
  "荊": "Kinh", "竺": "Trúc", "權": "Quyền", "逯": "Lục", "蓋": "Cái",
  "益": "Ích", "桓": "Hoàn", "俟": "Sĩ", "官": "Quan", "陽": "Dương",
  "人": "Nhân", "赫": "Hách", "皇": "Hoàng", "甫": "Phủ", "尉": "Úy",
  "澹": "Đạm", "冶": "Dã", "于": "Vu", "太": "Thái", "軒": "Hiên",
  "轅": "Viên", "令": "Lệnh", "狐": "Hồ", "離": "Ly", "鮮": "Tiên",
  "閭": "Lư", "丘": "Khâu", "徒": "Đồ", "亓": "Kỳ", "仉": "Chưởng",
  "督": "Đốc", "子": "Tử", "顓": "Chuyên", "漆": "Tất", "雕": "Điêu",
  "樂": "Nhạc", "壤": "Nhưỡng", "駟": "Tứ", "跋": "Bạt", "夾": "Giáp",
  "父": "Phụ", "穀": "Cốc", "梁": "Lương", "晉": "Tấn", "楚": "Sở",
  "法": "Pháp", "汝": "Nhữ", "鄢": "Yên", "塗": "Đồ", "干": "Can",
  "呼": "Hô", "延": "Diên", "歸": "Quy", "舌": "Thiệt", "微": "Vi",
  "帥": "Soái", "緱": "Câu", "亢": "Kháng", "況": "Huống", "有": "Hữu",
  "商": "Thương", "牟": "Mâu", "佘": "Xa", "佴": "Nhi", "賞": "Thưởng",
  "哈": "Cáp", "譙": "Tiếu", "笪": "Đát", "年": "Niên", "佟": "Đồng",
  "第": "Đệ", "言": "Ngôn",
  "趙": "Triệu", "褚": "Chử", "衛": "Vệ", "韓": "Hàn", "秦": "Tần",
  "尤": "Vưu", "孔": "Khổng", "陶": "Đào", "姜": "Khương", "戚": "Thích",
  "喻": "Dụ", "竇": "Đậu", "奚": "Hề", "郎": "Lang", "魯": "Lỗ",
  "韋": "Vi", "苗": "Miêu", "俞": "Du", "任": "Nhiệm", "柳": "Liễu",
  "酆": "Phong", "史": "Sử", "費": "Phí", "廉": "Liêm", "雷": "Lôi",
  "倪": "Nghê", "滕": "Đằng", "殷": "Ân", "畢": "Tất", "郝": "Hách",
  "時": "Thời", "皮": "Bì", "齊": "Tề", "伍": "Ngũ", "卜": "Bốc",
  "孟": "Mạnh", "穆": "Mục", "尹": "Doãn", "湛": "Trạm", "汪": "Uông",
  "祁": "Kỳ", "禹": "Vũ", "狄": "Địch", "米": "Mễ", "貝": "Bối",
  "臧": "Tang", "計": "Kế", "伏": "Phục", "談": "Đàm", "宋": "Tống",
  "茅": "Mao", "舒": "Thư", "項": "Hạng", "閔": "Mẫn", "席": "Tịch",
  "麻": "Ma", "婁": "Lâu", "田": "Điền", "凌": "Lăng", "支": "Chi",
  "昝": "Tảm", "經": "Kinh", "房": "Phòng", "賁": "Bí", "濁": "Trọc",
  "印": "Ấn", "鬱": "Úc", "卻": "Khước", "套": "Sáo", "晃": "Hoảng",
  "万": "Vạn", "閆": "Diêm", "得": "Đắc", "飼": "Tự", "帶": "Đới",
  "盼": "Phán", "笑": "Tiếu", "惜": "Tích", "怨": "Oán", "嫌": "Hiềm",
  "巧": "Xảo", "娜": "Na", "倩": "Thiến", "姿": "Tư", "同": "Đồng",
  "燦": "Sán", "蕙": "Huệ", "曼": "Mạn", "妮": "Ni", "瑩": "Oánh",
  "楠": "Nam", "栗": "Lật", "梨": "Lê", "條": "Điều", "案": "Án",
  "洛": "Lạc", "淋": "Lâm", "涼": "Lương", "岡": "Cương", "墉": "Dung",
  "鎰": "Dật", "鏞": "Dung", "鎔": "Dung", "昉": "Phảng", "普": "Phổ",
  "暄": "Huyên", "暖": "Noãn", "曉": "Hiểu", "然": "Nhiên", "恥": "Sỉ",
  "悌": "Đê", "儉": "Kiệm", "讓": "Nhượng", "虛": "Hư", "肅": "Túc",
  "尊": "Tôn", "勤": "Cần", "篤": "Đốc", "敦": "Đôn", "博": "Bác",
  "齡": "Linh", "娣": "Đệ", "虹": "Hồng", "嵐": "Lam", "橙": "Trừng",
  "炎": "Viêm", "冰": "Băng", "笛": "Địch", "簫": "Tiêu", "韻": "Vận",
  "音": "Âm", "歌": "Ca", "女": "Nữ", "苦": "Khổ", "甜": "Điềm",
  "蜜": "Mật", "理": "Lý", "道": "Đạo", "恒": "Hằng", "存": "Tồn",
  "在": "Tại", "守": "Thủ", "護": "Hộ", "莉": "Lợi", "蓉": "Dung",
  "薇": "Vi", "菲": "Phi"
};

// 拼音轉換輔助表 (確保姓名絕不掉出中文字元)
const PINYIN_TABLE = {
  "鏗": "Keng", "煒": "Wei", "瑄": "Hsuan", "筑": "Chu", "綺": "Chi",
  "曜": "Yao", "宸": "Chen", "要": "Yao", "鈞": "Chun", "鈺": "Yu",
  "鑫": "Hsin", "詠": "Yung", "奕": "Yi", "宥": "Yu", "佑": "Yu",
  "祐": "Yu", "叡": "Jui", "喆": "Che", "愷": "Kai", "璿": "Hsuan",
  "瑋": "Wei", "珉": "Min", "妍": "Yen", "希": "Hsi", "霏": "Fei",
  "霓": "Ni", "馳": "Chih", "駿": "Chun", "逸": "Yi", "楷": "Kai",
  "倫": "Lun", "晟": "Sheng", "璟": "Ching", "瑀": "Yu", "璨": "Tsan",
  "爍": "Shuo", "翊": "Yi", "靖": "Ching", "霆": "Ting", "芊": "Chien",
  "筠": "Chun", "筱": "Hsiao", "媗": "Hsuan", "嫈": "Ying", "嫺": "Hsien",
  "嫻": "Hsien", "嫣": "Yen", "穎": "Ying", "歆": "Hsin", "昕": "Hsin",
  "昀": "Yun", "晞": "Hsi", "曄": "Yeh", "燁": "Yeh", "昊": "Hao",
  "昂": "Ang", "昇": "Sheng", "旻": "Min", "昆": "Kun", "昶": "Chang",
  "梵": "Fan", "柱": "Chu", "梓": "Tzu", "杰": "Chieh", "植": "Chih",
  "槐": "Huai", "榆": "Yu", "榛": "Chen", "樞": "Shu", "模": "Mo",
  "樣": "Yang", "機": "Chi", "橫": "Heng", "檀": "Tan", "櫻": "Ying",
  "冠": "Kuan", "樺": "Hua", "志": "Chih", "婷": "Ting", "凱": "Kai",
  "宇": "Yu", "翔": "Hsiang", "玲": "Ling", "萍": "Ping", "珍": "Chen",
  "琴": "Chin", "琳": "Lin", "欣": "Hsin", "怡": "Yi", "萱": "Hsuan",
  "涵": "Han", "晴": "Ching", "琪": "Chi", "佳": "Chia", "佩": "Pei",
  "珊": "Shan", "雯": "Wen", "銘": "Ming", "宏": "Hung", "偉": "Wei",
  "宗": "Tsung", "家": "Chia", "建": "Chien", "廷": "Ting", "庭": "Ting",
  "承": "Cheng", "哲": "Che", "瑞": "Jui", "豪": "Hao", "慶": "Ching",
  "陳": "Chen", "林": "Lin", "黃": "Huang", "張": "Chang", "李": "Li",
  "王": "Wang", "吳": "Wu", "劉": "Liu", "蔡": "Tsai", "楊": "Yang",
  "許": "Hsu", "鄭": "Cheng", "謝": "Hsieh", "洪": "Hung", "郭": "Kuo",
  "邱": "Chiu", "曾": "Tseng", "廖": "Liao", "賴": "Lai", "周": "Chou",
  "徐": "Hsu", "蘇": "Su", "葉": "Yeh", "莊": "Chuang", "呂": "Lu",
  "江": "Chiang", "何": "Ho", "蕭": "Hsiao", "羅": "Lo", "高": "Kao",
  "潘": "Pan", "簡": "Chien", "朱": "Chu", "彭": "Peng", "游": "Yu",
  "詹": "Chan", "胡": "Hu", "施": "Shih", "沈": "Shen", "柯": "Ko",
  "盧": "Lu", "余": "Yu", "翁": "Weng", "魏": "Wei", "孫": "Sun",
  "戴": "Tai", "范": "Fan", "方": "Fang", "鄧": "Teng", "杜": "Tu",
  "大": "Ta", "中": "Chung", "明": "Ming", "文": "Wen", "武": "Wu",
  "阿": "A", "美": "Mei", "麗": "Li", "玉": "Yu", "秀": "Hsiu",
  "春": "Chun", "秋": "Chiu", "冬": "Tung", "夏": "Hsia", "金": "Chin",
  "木": "Mu", "水": "Shui", "火": "Huo", "土": "Tu", "榮": "Jung",
  "華": "Hua", "富": "Fu", "貴": "Kuei", "福": "Fu", "壽": "Shou",
  "康": "Kang", "健": "Chien", "強": "Chiang", "順": "Shun", "發": "Fa",
  "旺": "Wang", "財": "Tsai", "寶": "Pao", "珠": "Chu", "英": "Ying",
  "雄": "Hsiung", "俊": "Chun", "傑": "Chieh", "仁": "Jen", "義": "Yi",
  "禮": "Li", "智": "Chih", "信": "Hsin", "忠": "Chung", "孝": "Hsiao",
  "德": "Te", "安": "An", "平": "Ping", "和": "Ho", "成": "Cheng",
  "功": "Kung", "達": "Ta", "雲": "Yun", "海": "Hai", "山": "Shan",
  "月": "Yueh", "星": "Hsing", "光": "Kuang", "生": "Sheng", "正": "Cheng",
  "清": "Ching", "泉": "Chuan", "松": "Sung", "柏": "Po", "竹": "Chu",
  "梅": "Mei", "蘭": "Lan", "菊": "Chu", "花": "Hua", "芳": "Fang",
  "芬": "Fen", "淑": "Shu", "惠": "Hui", "娟": "Chuan", "娥": "E",
  "鳳": "Feng", "凰": "Huang", "霞": "Hsia", "蓮": "Lien", "香": "Hsiang",
  "嬤": "Ma", "公": "Kung", "婆": "Po", "爺": "Yeh", "爸": "Pa",
  "媽": "Ma", "哥": "Ko", "弟": "Ti", "罔": "Wang", "市": "Shih",
  "腰": "Yao", "招": "Chao", "治": "Chih", "滿": "Man", "枝": "Chih",
  "桃": "Tao", "妹": "Mei", "嬌": "Chiao", "好": "Hao", "素": "Su",
  "碧": "Pi", "翠": "Tsui", "瓊": "Chiung", "雪": "Hsueh", "霜": "Shuang",
  "露": "Lu", "添": "Tien", "賜": "Szu", "祿": "Lu", "來": "Lai",
  "朝": "Chao", "欽": "Chin", "勝": "Sheng", "男": "Nan", "勇": "Yung",
  "茂": "Mao", "盛": "Sheng", "輝": "Hui", "耀": "Yao", "顯": "Hsien",
  "揚": "Yang", "樹": "Shu", "根": "Ken", "通": "Tung", "標": "Piao",
  "棟": "Tung", "樑": "Liang", "森": "Sen", "斌": "Pin", "彬": "Pin",
  "泰": "Tai", "祥": "Hsiang", "吉": "Chi", "豐": "Feng", "進": "Chin",
  "步": "Pu", "超": "Chao", "群": "Chun", "祖": "Tsu", "睿": "Jui",
  "皓": "Hao", "瀚": "Han", "辰": "Chen", "昱": "Yu", "晨": "Chen",
  "霖": "Lin", "毅": "Yi", "捷": "Chieh", "謙": "Chien", "遠": "Yuan",
  "雅": "Ya", "潔": "Chieh", "真": "Chen", "貞": "Chen", "慧": "Hui",
  "晶": "Ching", "愛": "Ai", "心": "Hsin", "慈": "Tzu", "小": "Hsiao",
  "天": "Tien", "地": "Ti", "乾": "Chien", "坤": "Kun", "元": "Yuan",
  "亨": "Heng", "利": "Li", "邦": "Pang", "國": "Kuo", "保": "Pao",
  "定": "Ting", "長": "Chang", "川": "Chuan", "河": "Ho", "湖": "Hu",
  "池": "Chih", "潭": "Tan", "洲": "Chou", "伯": "Po", "仲": "Chung",
  "叔": "Shu", "季": "Chi", "姐": "Chieh", "桂": "Kuei", "錦": "Chin",
  "繡": "Hsiu", "瑟": "Se", "彩": "Tsai", "仙": "Hsien", "妙": "Miao",
  "溫": "Wen", "崔": "Tsui", "賈": "Chia", "路": "Lu", "毛": "Mao",
  "銳": "Jui", "鋒": "Feng", "鎮": "Chen", "銓": "Chuan", "棠": "Tang",
  "楓": "Feng", "榕": "Jung", "桐": "Tung", "樟": "Chang", "沛": "Pei",
  "泳": "Yung", "浩": "Hao", "淳": "Chun", "淵": "Yuan", "濤": "Tao",
  "鴻": "Hung", "澎": "Peng", "潮": "Chao", "澤": "Tse", "濟": "Chi",
  "潤": "Jun", "炳": "Ping", "炯": "Chiung", "炫": "Hsuan", "烽": "Feng",
  "煥": "Huan", "煜": "Yu", "熙": "Hsi", "燃": "Jan", "培": "Pei",
  "均": "Chun", "城": "Cheng", "基": "Chi", "堂": "Tang", "堯": "Yao",
  "增": "Tseng", "壇": "Tan", "壁": "Pi", "壕": "Hao", "如": "Ju",
  "意": "Yi", "銀": "Yin", "憲": "Hsien", "政": "Cheng", "隆": "Lung",
  "昌": "Chang", "興": "Hsing", "喜": "Hsi", "日": "Jih", "島": "Tao",
  "岩": "Yen", "峰": "Feng", "嶺": "Ling", "崗": "Kang", "岳": "Yueh",
  "石": "Shih", "鐵": "Tieh", "銅": "Tung", "鋼": "Kang", "錫": "Hsi",
  "鑑": "Chien", "鐘": "Chung", "鍾": "Chung", "鑽": "Tsuan", "環": "Huan",
  "瑛": "Ying", "瑜": "Yu", "瑤": "Yao", "瑾": "Chin", "璇": "Hsuan",
  "瑚": "Hu", "瓏": "Lung", "荷": "Ho", "芝": "Chih", "草": "Tsao",
  "敏": "Min", "靜": "Ching", "端": "Tuan", "賢": "Hsien", "良": "Liang",
  "善": "Shan", "情": "Ching", "恩": "En", "念": "Nien", "思": "Ssu",
  "想": "Hsiang", "懷": "Huai", "憶": "Yi", "願": "Yuan", "寬": "Kuan",
  "厚": "Hou", "誠": "Cheng", "樸": "Pu", "純": "Chun", "實": "Shih",
  "遜": "Hsun", "謹": "Chin", "慎": "Shen", "恭": "Kung", "敬": "Ching",
  "剛": "Kang", "猛": "Meng", "烈": "Lieh", "彥": "Yen", "儒": "Ju",
  "學": "Hsueh", "書": "Shu", "章": "Chang", "翰": "Han", "墨": "Mo",
  "研": "Yen", "究": "Chiu", "創": "Chuang", "造": "Tsao", "立": "Li",
  "業": "Yeh", "開": "Kai", "展": "Chan", "拓": "To", "升": "Sheng",
  "騰": "Teng", "飛": "Fei", "鵬": "Peng", "鶴": "Ho", "鷹": "Ying",
  "燕": "Yen", "雀": "Chueh", "虎": "Hu", "豹": "Pao", "龍": "Lung",
  "麟": "Lin", "龜": "Kuei", "青": "Ching", "綠": "Lu", "紅": "Hung",
  "赤": "Chih", "白": "Pai", "黑": "Hei", "玄": "Hsuan", "紫": "Tzu",
  "丹": "Tan", "彤": "Tung", "絢": "Hsuan", "燦": "Tsan", "爛": "Lan",
  "煌": "Huang", "照": "Chao", "暉": "Hui", "曦": "Hsi", "旭": "Hsu",
  "東": "Tung", "西": "Hsi", "南": "Nan", "北": "Pei", "上": "Shang",
  "下": "Hsia", "前": "Chien", "後": "Hou", "左": "Tso", "右": "Yu",
  "一": "I", "二": "Erh", "三": "San", "四": "Szu", "五": "Wu",
  "六": "Liu", "七": "Chi", "八": "Pa", "九": "Chiu", "十": "Shih",
  "百": "Pai", "千": "Chien", "萬": "Wan", "億": "I", "兆": "Chao",
  "初": "Chu", "始": "Shih", "終": "Chung", "永": "Yung", "久": "Chiu",
  "恆": "Heng", "常": "Chang", "寧": "Ning", "睦": "Mu", "友": "Yu",
  "朋": "Peng", "賓": "Pin", "客": "Ko", "鄰": "Lin", "里": "Li",
  "鄉": "Hsiang", "村": "Tsun", "州": "Chou", "省": "Sheng", "縣": "Hsien",
  "府": "Fu", "室": "Shih", "門": "Men", "戶": "Hu", "居": "Chu",
  "宅": "Chai", "園": "Yuan", "院": "Yuan", "樓": "Lou", "閣": "Ko",
  "亭": "Ting", "榭": "Hsieh", "臺": "Tai", "台": "Tai", "源": "Yuan",
  "溪": "Hsi", "澗": "Chien", "瀧": "Lung", "浪": "Lang", "波": "Po",
  "瀾": "Lan", "洋": "Yang", "滄": "Tsang", "溟": "Ming", "浮": "Fu",
  "泛": "Fan", "深": "Shen", "澈": "Che", "澄": "Cheng", "淨": "Ching",
  "洗": "Hsi", "滌": "Ti", "沐": "Mu", "浴": "Yu", "灌": "Kuan",
  "溉": "Kai", "溢": "I", "滔": "Tao", "湧": "Yung", "湃": "Pai",
  "汐": "Hsi", "汛": "Hsun", "津": "Chin", "渡": "Tu", "舟": "Chou",
  "船": "Chuan", "帆": "Fan", "航": "Hang", "艦": "Chien", "舵": "To",
  "錨": "Mao", "岸": "An", "港": "Kang", "灣": "Wan", "浦": "Pu",
  "濱": "Pin", "灘": "Tan", "渚": "Chu", "嶼": "Yu", "妤": "Yu",
  "婕": "Chieh", "茜": "Chien", "薇": "Wei", "蕾": "Lei", "芷": "Chih",
  "芮": "Jui", "芯": "Hsin", "茉": "Mo", "莉": "Li", "菲": "Fei",
  "蓉": "Jung", "蓓": "Pei", "蔓": "Man", "蓁": "Chen", "藍": "Lan",
  "蔚": "Wei", "藝": "I", "芸": "Yun", "芹": "Chin", "茵": "Yin",
  "茹": "Ju", "莎": "Sha", "菁": "Ching", "菱": "Ling", "萌": "Meng",
  "蘿": "Lo", "蔣": "Chiang", "薛": "Hsueh", "薄": "Po", "藻": "Tsao",
  "蘆": "Lu", "阮": "Nguyen", "姚": "Dao", "邵": "Thieu", "錢": "Tien",
  "湯": "Thang", "嚴": "Nghiem", "陸": "Lu", "包": "Pao", "童": "Tung",
  "鄒": "Trau", "巫": "Wu", "卓": "Cho", "顏": "Yen", "連": "Lien",
  "丁": "Đinh", "馬": "Ma", "董": "Đong", "唐": "Đuong", "馮": "Phung",
  "程": "Cheng", "曹": "Tao", "袁": "Vien", "傅": "Fu", "歐": "Ou",
  "粘": "Nien", "紀": "Chi", "涂": "Tu", "鄔": "Wu", "刁": "Tiao",
  "卞": "Pien", "邢": "Hsing", "荀": "Hsun", "邰": "Tai", "虞": "Yu",
  "靳": "Chin", "鮑": "Pao", "閻": "Yen", "霍": "Huo", "繆": "Miu",
  "譚": "Tan", "顧": "Ku", "龔": "Kung", "龐": "Pang", "賀": "Ho",
  "樊": "Fan", "焦": "Chiao", "岑": "Tsen", "莫": "Mo", "裘": "Chiu",
  "仇": "Chiu", "祝": "Chu", "辜": "Ku", "駱": "Lo", "屈": "Chu",
  "葛": "Ko", "儲": "Chu", "柴": "Chai", "耿": "Keng", "牛": "Niu",
  "牧": "Mu", "羊": "Yang", "鹿": "Lu", "熊": "Hsiung", "遲": "Chih",
  "危": "Wei", "管": "Kuan", "冷": "Leng", "甘": "Kan", "蒙": "Meng",
  "邊": "Pien", "宮": "Kung", "解": "Hsieh", "應": "Ying", "宣": "Hsuan",
  "郁": "Yu", "單": "Shan", "杭": "Hang", "諸": "Chu", "鈕": "Niu",
  "嵇": "Chi", "滑": "Hua", "裴": "Pei", "於": "Yu", "甄": "Chen",
  "麴": "Chu", "封": "Feng", "羿": "I", "汲": "Chi", "邴": "Ping",
  "糜": "Mi", "井": "Ching", "段": "Tuan", "烏": "Wu", "巴": "Pa",
  "弓": "Kung", "隗": "Wei", "谷": "Ku", "車": "Che", "侯": "Hou",
  "宓": "Mi", "蓬": "Peng", "全": "Chuan", "郗": "Hsi", "班": "Pan",
  "仰": "Yang", "伊": "I", "欒": "Luan", "暴": "Pao", "郜": "Kao",
  "符": "Fu", "景": "Ching", "束": "Shu", "幸": "Hsing", "司": "Ssu",
  "韶": "Shao", "黎": "Li", "薊": "Chi", "宿": "Su", "蒲": "Pu",
  "從": "Tsung", "鄂": "O", "索": "So", "咸": "Hsien", "籍": "Chi",
  "藺": "Lin", "屠": "Tu", "喬": "Chiao", "陰": "Yin", "胥": "Hsu",
  "能": "Neng", "蒼": "Tsang", "雙": "Shuang", "聞": "Wen", "莘": "Shen",
  "黨": "Tang", "翟": "Chai", "貢": "Kung", "勞": "Lao", "逄": "Pang",
  "姬": "Chi", "申": "Shen", "扶": "Fu", "堵": "Tu", "冉": "Jan",
  "宰": "Tsai", "酈": "Li", "雍": "Yung", "郤": "Hsi", "璩": "Chu",
  "桑": "Sang", "濮": "Pu", "扈": "Hu", "冀": "Chi", "郟": "Chia",
  "尚": "Shang", "農": "Nung", "別": "Pieh", "晏": "Yen", "瞿": "Chu",
  "充": "Chung", "慕": "Mu", "習": "Hsi", "宦": "Huan", "艾": "Ai",
  "魚": "Yu", "容": "Jung", "向": "Hsiang", "古": "Ku", "易": "I",
  "戈": "Ko", "庾": "Yu", "暨": "Chi", "衡": "Heng", "都": "Tu",
  "弘": "Hung", "匡": "Kuang", "寇": "Kou", "廣": "Kuang", "闕": "Chueh",
  "殳": "Shu", "沃": "Wo", "越": "Yueh", "夔": "Kuei", "師": "Shih",
  "鞏": "Kung", "厙": "She", "聶": "Nieh", "晁": "Chao", "勾": "Kou",
  "敖": "Ao", "融": "Jung", "訾": "Tzu", "辛": "Hsin", "闞": "Kan",
  "那": "Na", "饒": "Jao", "空": "Kung", "毋": "Wu", "沙": "Sha",
  "乜": "Nieh", "養": "Yang", "鞠": "Chu", "須": "Hsu", "巢": "Chao",
  "關": "Kuan", "蒯": "Kuai", "相": "Hsiang", "查": "Cha", "后": "Hou",
  "荊": "Ching", "竺": "Chu", "權": "Chuan", "逯": "Lu", "蓋": "Kai",
  "益": "I", "桓": "Huan", "俟": "Szu", "官": "Kuan", "陽": "Yang",
  "人": "Jen", "赫": "Ho", "皇": "Huang", "甫": "Fu", "尉": "Wei",
  "澹": "Tan", "冶": "Yeh", "于": "Yu", "太": "Tai", "軒": "Hsuan",
  "轅": "Yuan", "令": "Ling", "狐": "Hu", "離": "Li", "鮮": "Hsien",
  "閭": "Lu", "丘": "Chiu", "徒": "Tu", "亓": "Chi", "仉": "Chang",
  "督": "Tu", "子": "Tzu", "顓": "Chuan", "漆": "Chi", "雕": "Tiao",
  "樂": "Yueh", "壤": "Jang", "駟": "Szu", "跋": "Pa", "夾": "Chia",
  "父": "Fu", "穀": "Ku", "梁": "Liang", "晉": "Chin", "楚": "Chu",
  "法": "Fa", "汝": "Ju", "鄢": "Yen", "塗": "Tu", "干": "Kan",
  "呼": "Hu", "延": "Yen", "歸": "Kuei", "舌": "She", "微": "Wei",
  "帥": "Shuai", "緱": "Kou", "亢": "Kang", "況": "Kuang", "有": "Yu",
  "商": "Shang", "牟": "Mou", "佘": "She", "佴": "Erh", "賞": "Shang",
  "哈": "Ha", "譙": "Chiao", "笪": "Ta", "年": "Nien", "佟": "Tung",
  "第": "Ti", "言": "Yen",
  "趙": "Chao", "褚": "Chu", "衛": "Wei", "韓": "Han", "秦": "Chin",
  "尤": "Yu", "孔": "Kung", "陶": "Tao", "姜": "Chiang", "戚": "Chi",
  "喻": "Yu", "竇": "Tou", "奚": "Hsi", "郎": "Lang", "魯": "Lu",
  "韋": "Wei", "苗": "Miao", "俞": "Yu", "任": "Jen", "柳": "Liu",
  "酆": "Feng", "史": "Shih", "費": "Fei", "廉": "Lien", "雷": "Lei",
  "倪": "Ni", "滕": "Teng", "殷": "Yin", "畢": "Pi", "郝": "Hao",
  "時": "Shih", "皮": "Pi", "齊": "Chi", "伍": "Wu", "卜": "Pu",
  "孟": "Meng", "穆": "Mu", "尹": "Yin", "湛": "Chan", "汪": "Wang",
  "祁": "Chi", "禹": "Yu", "狄": "Ti", "米": "Mi", "貝": "Pei",
  "臧": "Tsang", "計": "Chi", "伏": "Fu", "談": "Tan", "宋": "Sung",
  "茅": "Mao", "舒": "Shu", "項": "Hsiang", "閔": "Min", "席": "Hsi",
  "麻": "Ma", "婁": "Lou", "田": "Tien", "凌": "Ling", "支": "Chih",
  "昝": "Tsan", "經": "Ching", "房": "Fang", "賁": "Pen", "濁": "Cho",
  "印": "Yin", "鬱": "Yu", "卻": "Chueh", "套": "Tao", "晃": "Huang",
  "万": "Wan", "閆": "Yen", "得": "Te", "飼": "Szu", "帶": "Tai",
  "盼": "Pan", "笑": "Hsiao", "惜": "Hsi", "怨": "Yuan", "嫌": "Hsien",
  "巧": "Chiao", "娜": "Na", "倩": "Chien", "姿": "Tzu", "同": "Tung",
  "燦": "Tsan", "蕙": "Hui", "曼": "Man", "妮": "Ni", "瑩": "Ying",
  "楠": "Nan", "栗": "Li", "梨": "Li", "條": "Tiao", "案": "An",
  "洛": "Lo", "淋": "Lin", "涼": "Liang", "岡": "Kang", "墉": "Yung",
  "鎰": "Yi", "鏞": "Yung", "鎔": "Yung", "昉": "Fang", "普": "Pu",
  "暄": "Hsuan", "暖": "Nuan", "曉": "Hsiao", "然": "Jan", "恥": "Chih",
  "悌": "Ti", "儉": "Chien", "讓": "Jang", "虛": "Hsu", "肅": "Su",
  "尊": "Tsun", "勤": "Chin", "篤": "Tu", "敦": "Tun", "博": "Po",
  "齡": "Ling", "娣": "Ti", "虹": "Hung", "嵐": "Lan", "橙": "Cheng",
  "炎": "Yen", "冰": "Ping", "笛": "Ti", "簫": "Hsiao", "韻": "Yun",
  "音": "Yin", "歌": "Ko", "女": "Nu", "苦": "Ku", "甜": "Tien",
  "蜜": "Mi", "理": "Li", "道": "Tao", "恒": "Heng", "存": "Tsun",
  "在": "Tsai", "守": "Shou", "護": "Hu", "莉": "Li", "蓉": "Jung",
  "薇": "Wei", "菲": "Fei"
};

/**
 * 以內建離線字典產生中文姓名的建議外語音譯（不呼叫任何 API）。
 * 只有每一個姓名字都能對應時才回傳，避免略過缺字而產生不完整姓名。
 */
function suggestSecondLanguageName(chineseName, langCode = 'vi') {
  if (!chineseName || typeof chineseName !== 'string' || langCode === 'zh-only') return '';
  // 1. 去除括號註記、斜線註記、稱謂與空白（如「（男）」、「(個案)」、「/男」、「先生」、「女士」）
  let cleanName = chineseName
    .replace(/\s+/g, '')
    .replace(/[\(（\[【].*?[\)）\]】]/g, '')
    .replace(/[\/／][男女]/g, '')
    .replace(/(?:先生|女士|阿公|阿嬤|伯伯|婆婆|小姐|長者|長輩|個案|住民|病患)$/g, '');
  // 2. 僅保留中文字元
  const chars = Array.from(cleanName).filter(char => /[\u4e00-\u9fff]/.test(char));
  if (!chars.length) return '';

  if (langCode === 'vi') {
    const result = chars.map(char => {
      if (HAN_VIET_DICT[char]) return HAN_VIET_DICT[char];
      if (PINYIN_TABLE[char]) return PINYIN_TABLE[char];
      return '';
    });
    if (result.some(part => !part)) return '';
    const trans = result.join(' ');
    // 嚴格保證絕無中文殘留
    return /[\u4e00-\u9fa5]/.test(trans) ? '' : trans;
  }

  // 英語、印尼、菲律賓、泰語等拼音音譯格式 (例如：Wang, Da-Ming)
  const pinyinParts = chars.map(char => {
    if (PINYIN_TABLE[char]) return PINYIN_TABLE[char];
    if (HAN_VIET_DICT[char]) return HAN_VIET_DICT[char].normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    return '';
  });
  if (pinyinParts.some(part => !part)) return '';

  if (pinyinParts.length > 1) {
    const res = `${pinyinParts[0]}, ${pinyinParts.slice(1).join('-')}`;
    return /[\u4e00-\u9fa5]/.test(res) ? '' : res;
  } else if (pinyinParts.length === 1) {
    return /[\u4e00-\u9fa5]/.test(pinyinParts[0]) ? '' : pinyinParts[0];
  }

  return '';
}

// 供全域環境引用
if (typeof window !== 'undefined') {
  window.CARE_DICTIONARY = CARE_DICTIONARY;
  window.CARE_ALIASES = CARE_ALIASES;
  window.HAN_VIET_DICT = HAN_VIET_DICT;
  window.PINYIN_TABLE = PINYIN_TABLE;
  window.suggestSecondLanguageName = suggestSecondLanguageName;
}
